/**
 * Snapshot of the live YouTube pull (CLAUDE.md §12), written by `pnpm discover` on 2026-09-16.
 * The seed loads these as Seeded rows; they flip to Live only when the running build re-fetches them.
 * Public professional-account data only. Do not edit by hand; re-run `pnpm discover`.
 */
export type YoutubeSnapshotRow = {
  handle: string;
  external_id: string;
  display_name: string;
  url: string;
  followers: number;
  engagement_rate: number | null;
  avg_views: number | null;
  bio: string;
  recent_titles: string[];
};

export const YOUTUBE_SNAPSHOT: YoutubeSnapshotRow[] = [
  {
    "handle": "@drpimplepopper",
    "external_id": "UCgrsF4TYwmrV0QsXb8AoeHQ",
    "display_name": "Dr. Pimple Popper",
    "url": "https://www.youtube.com/@drpimplepopper",
    "followers": 9130000,
    "engagement_rate": 0.0007,
    "avg_views": 420869,
    "bio": "Welcome to the world of Dr. Pimple Popper, the one and only Sandra Lee, MD! As a board certified dermatologist, skin cancer surgeon, and cosmetic surgeon, I am a highly sought-after  expert in the field of dermatology. \n\nOn this channel, you'll find a treasure trove of videos that offer a window into my world. \nHopefully you'll learn about various skin conditions, hair  and nail issues, and cutting-edge cosmetic surgery techniques. Whether you're struggling with  blackheads, acne, cysts, warts, or looking for Botox, fillers, or liposuction, you'll find helpful advice and information here. \n\nBut this channel isn't just about skin care - it's about the amazing people I encounter every day.  You'll get to know some of my incredible patients and their stories, and maybe even fall in love  with dermatology just as much as I have! \n\n",
    "recent_titles": [
      "What is Steatocystoma Multiplex? | Dr. Pimple Popper vs. Steatocystomas",
      "One Patient. 4 Steatocystoma Sessions. | Dr. Pimple Popper",
      "Big Blackheads On The Nose Can Be Caused By Rosacea?",
      "It was a slippery little guy...⁠ Watch both procedures at the link ✌️❤️💥⁠",
      "Back Blackhead Cleanup ✌️❤️💥",
      "Two of my most famous Dilated Pores of Winer. Are one of these your fave, #popaholics?⁠",
      "Who knew that having a furrowed brow could be an advantage??⁠⁠",
      "Dr. Pimple Popper vs. The Uncomfortable, Inguinal Lipoma",
      "Consider this your reminder to give your ears a little skincare love, too. 💛⁠",
      "What do you think? 👽",
      "What is a Dilated Pore of Winer (and how do you prevent it?)",
      "Two Cysts on Two Different Temples 👉💥👈"
    ]
  },
  {
    "handle": "@doctorly",
    "external_id": "UCHCZnC9akNA9pBP7aJGNKdg",
    "display_name": "Doctorly",
    "url": "https://www.youtube.com/@doctorly",
    "followers": 3580000,
    "engagement_rate": 0.0006,
    "avg_views": 148087,
    "bio": "Evidenced-based skin care, dermatology, and medicine. Channel run by double Board-Certified Dermatologists with the goal of providing accurate, up-to-date information to our subscribers with full transparency. Thank you for following along with us. - Dr. Shah and Dr. Maxfield\n",
    "recent_titles": [
      "Aging Gracefully: What 5 YEARS Have Taught Us About Our Skincare",
      "Treat Itchy Fingers FAST: Dyshidrotic Eczema",
      "Derms LOVE Viral Tretinoin & Azelaic Acid Routine | Doctorly #shorts",
      "GLASS SKIN? Tretinoin & Azelaic Acid Viral Routine Debunked",
      "Introducing the Doctorly Games | Doctorly #shorts",
      "Stop WASTING Money on Skincare | Doctorly #shorts",
      "THIS is Hydration",
      "Laser vs LED vs Microcurrent: Which Anti-Aging Device Actually Works?",
      "You're Spending WAY Too Much on Skincare",
      "Puffy Eyes? Try This | Doctorly #shorts",
      "We Put Dermatology Residents to the Test for $60,000 | Introducing Doctorly Games",
      "Where to start your skincare?"
    ]
  },
  {
    "handle": "@drkhaledsadek",
    "external_id": "UC1uQSMobq0kPWSrLz4dc49g",
    "display_name": "Dr Khaled Sadek",
    "url": "https://www.youtube.com/@drkhaledsadek",
    "followers": 1190000,
    "engagement_rate": 0.004,
    "avg_views": 207106,
    "bio": "Dr Khaled Sadek provides surgical and non-surgical cosmetic work: focusing on cyst and lipoma removal. He is also experienced in anti-wrinkle facial injections, in addition to being a London based GP. His clinics are located in Chelsea London. \n\nDr Khaled Sadek\n295 Kings Road\nChelsea\nLondon\nSW3 5EP\n\nwww.lipomacyst.com\n\n0203 474 6300 \n[email removed]",
    "recent_titles": [
      "Before and after #cystremoval #drkhaledsadek LIPOMACYST.com",
      "Better out the name #cystremoval #drkhaledsadek",
      "Dr Khaled explains what happens when leave cyst for too long| hair loss scarring disfiguration ￼",
      "Dr Khaled explains #cystremoval #drkhaledsadek",
      "Help is not too far away LipomaCyst.com with Dr Khaled Sadek #cystremoval",
      "Milking the cyst on the daily #cystremoval #cystremoval dr Khaled sadek",
      "Full video cyst #cystremoval #blackhead #drkhaledsadek",
      "Before & After #cystremoval dr Khaled Sadek LipomaCyst.com",
      "#cystremoval Dr Khaled Sadek with LipomaCyst.Com",
      "Massive scalp cyst removal #cystremoval #drkhaledsadek",
      "Full video #cystremoval dr khaled sadek",
      "Skin cyst removal in London LipomaCyst.com dr khaled sadek"
    ]
  },
  {
    "handle": "@labmuffinbeautyscience",
    "external_id": "UCg6P323bLV4zMSWFqFhvWMg",
    "display_name": "Lab Muffin Beauty Science",
    "url": "https://www.youtube.com/@labmuffinbeautyscience",
    "followers": 861000,
    "engagement_rate": 0.0022,
    "avg_views": 32558,
    "bio": "I’m Michelle, a science educator and chemistry PhD from Sydney, Australia. I’m here to help you work out which beauty products are worth buying and which aren’t, using science!\n\nI started Lab Muffin because I was frustrated that there weren't enough easy-to-understand explanations of the science behind beauty products. I firmly believe that anyone can understand the science behind skincare and beauty.\n\nFor business/PR enquiries: [email removed]\n\nDISCLAIMER: I am not a medical doctor. Care has been taken to ensure the accuracy of the information here, but it is provided for education and research purposes only and is not intended to be a substitute for professional medical advice, diagnosis or treatment. Always seek the advice of a qualified health provider regarding any medical conditions. No liability is accepted for any injury, loss or damage incurred by use of or reliance on the information provided by me.",
    "recent_titles": [
      "Naturopath vs chemist: endocrine disruptors in sunscreen",
      "Dry shampoo is toxic??",
      "AI companies won't make their products safer",
      "Moisturiser isn't working anymore? (ad)",
      "Why AI chatbots are bad at science",
      "The \"paid testimonial ban\" isn't just about paid ads",
      "This law might be making skin cancer worse",
      "AD What is Melasyl? @LOrealParisAU Melasyl Creamy Serum #skincare #lorealparis #melasyl",
      "Sunscreens and other skincare I've been enjoying (Clarins ad)",
      "AD There are lots of myths around which actives you can and can’t layer - let’s do some debunking!",
      "Beware of lash serums!",
      "Fragrances are toxic?"
    ]
  },
  {
    "handle": "@acnetreatmenthuongdanang",
    "external_id": "UCViR3aeehZPMnx9w49DhJPw",
    "display_name": "Acne treatment Hương Đà Nẵng",
    "url": "https://www.youtube.com/@acnetreatmenthuongdanang",
    "followers": 706000,
    "engagement_rate": 0.0031,
    "avg_views": 184137,
    "bio": "This is new channel of \"Acne treatment Hương official\".\nPlease subscribe my new channel to watch latest videos.\nGuide how to get acne cores, get effective acne but not swollen, attractive and high technology level.\n\nFanPage: Hương Trị Mụn\nTel: 0904771370\nAddress: Trần Thị Diễm Hương, 7 Mộc Bài 1 Street, Liên Chiểu District, Đà Nẵng City, Việt Nam (Tel: 0904771370)\n[Facebook]\nhttps://www.facebook.com/diemhuongs200279\nhttps://www.facebook.com/acnetreatmenthuong\n[website]\nhttps://www.acnehuong.com/\nOld channel: http://www.youtube.com/c/AcnetreatmentHươngofficial\nEmail: [email removed]\n\n=====================================\n#Hương Đà Nẵng #acne treatment #Hương official #acne removal #inflammatory \n#skin care #hidden acne #pimple #scar removal #whitehead\n#blackheads #blackhead extraction #whiteheads extraction #poping\n#putules #papules #cysts #pimple popper blackhead #bamboo tube\n#mụn #nặn mụn #điều trị mụn #spa #chăm sóc da #mụn sẩ",
    "recent_titles": [
      "Acne Treatment Huong Da Nan#member#short#Coming soon",
      "Acne Treatment Huong Da Nang#752#Huong's staff_ Blackheads Long time no see.",
      "Acne Treatment Huong Da Nang# 022 | 2023",
      "Acne Treatment Huong Da Nang# membership 010 |  | 2023",
      "Acne Treatment Huong Da Nang# 038 |  Loyal fans Mai Part 1",
      "Acne Treatment Huong Da Nang#750#Huong's staff_ Balckheads",
      "Acne Treatment Huong Da Nang#749#Huong's staff_ Balckheads",
      "Acne Treatment Huong Da Nang#746#Huong's staff_ Part2 Blackheads and inflammation TET Holiday",
      "Acne Treatment Huong Da Nang#748#Huong's staff_ Part1 Blackheads and inflammation TET Holiday",
      "Acne Treatment Huong Da Nang#750#Happy New Year, TET Holiday",
      "Acne Treatment Huong Da Nang#746#Huong's staff_ Blackheads appear on the skin.",
      "Acne Treatment Huong Da Nang#746#Huong's staff_ Blackheads that have dried out can be removed easily"
    ]
  },
  {
    "handle": "@phongkhamhhvclinic",
    "external_id": "UCkHch-Hj9L90FyIz4gM1dPQ",
    "display_name": "Phòng Khám Da Liễu HHV Clinic",
    "url": "https://www.youtube.com/@phongkhamhhvclinic",
    "followers": 674000,
    "engagement_rate": 0.0026,
    "avg_views": 220994,
    "bio": "PHÒNG KHÁM DA LIỄU HHV CLINIC\n-\tChuyên điều trị: Mụn, sẹo, nám, thâm…\n-\tỨng dụng công nghệ tiên tiến \n-\tBác sĩ nhiều năm kinh nghiệm\n-\tĐiều trị thành công cho hàng triệu khách hàng\n-----------------------------\nPHÒNG KHÁM DA LIỄU HHV CLINIC - GIẢI PHÁP AN TOÀN CHO LÀN DA VIỆT\n📍 Địa chỉ: 652/12 Cộng Hòa, P13, Tân Bình, TP.HCM\n📍 Hotline: 0903 887 049 - 0969 462 327\n📍 Website: https://www.hvclinic.vn\n📍 Zalo: http://zalo.me/0903887049\n📍 https://www.tiktok.com/@hhvclinic\n📍 https://www.youtube.com/phongkhamdalieuhhvclinic\n📍 https://www.instagram.com/hhvclinicphongkhamdalieu/\n\n#hhvclinic #trimuntritham #trimun #trimunhieuqua #trimunuytin #triseo #triseoro #trinam #trimuntanbinh #trimunvinhvien\n\n",
    "recent_titles": [
      "Nặn mụn áp xe vùng Mông",
      "Điều trị mụn áp xe vùng Mông - Tại phòng khám da liễu HHV Clinic.",
      "Lấy nhân mụn áp xe vùng Mông",
      "Điều trị mụn áp xe vùng Mông - Tại phòng khám da liễu HHV Clinic.",
      "Mụn áp xe sưng to viêm vùng Mông",
      "Nặn mụn nhọt hoại tử ở Mông",
      "Điều trị mụn áp xe vùng má - Tại phòng khám da liễu HHV Clinic.",
      "Mụn áp xe vùng má",
      "Điều trị mụn u nang bã chai cứng nhiều năm - Tại phòng phám da liễu HHV Clinic (Part 2)",
      "Nặn mụn u nang bã",
      "Nặn mụn u nang bã",
      "Điều trị mụn u nang bã chai cứng nhiều năm - Tại phòng phám da liễu HHV Clinic (Part 1)"
    ]
  },
  {
    "handle": "@acnetreatmenthuongofficial",
    "external_id": "UC4MNOamHO1Bb0EW3QgOkgRw",
    "display_name": "Acne treatment Hương official",
    "url": "https://www.youtube.com/@acnetreatmenthuongofficial",
    "followers": 118000,
    "engagement_rate": 0.0263,
    "avg_views": 307365,
    "bio": "Hướng dẫn cách lấy nhân mụn, lấy nhân mụn hiệu quả không sưng, hấp dẫn, kỹ thuật cao.\nNew youtube channel: https://www.youtube.com/channel/UCQrSQJJJZTbgwuJkGi8XfIQ\nFanPage: Hương Trị Mụn\n  https://www.facebook.com/acnetreatmenthuong/\nFacebook:\n  https://www.facebook.com/diemhuongs200279",
    "recent_titles": [
      "ACne Treatment Huong official",
      "Relax with Acne Treatment Huong official # 004",
      "Enjoy Your Day with Acne treatment Huong official",
      "Acne Treatment Huong official",
      "Get inflamed acne for the boy",
      "[ Acne treatment Hương official ] Clean blackheads for lady",
      "[ Acne hide ] Hidden acne because use wrong drug",
      "[ Acne treatment Hương official ] Treating hidden acne, bran acne",
      "[ Blackhead ] get blackheads for young sister",
      "[ whiteheads ] Get your acne name Hoang ( official video )",
      "Acne pea | get pustules clean  ( Official Video )",
      "Acne treatment Hương beauty | My new channel"
    ]
  },
  {
    "handle": "@zeinebkhenissi",
    "external_id": "UC710Yh8vi3jAFgkPGku5TMA",
    "display_name": "Spécialiste de la santé — Sans filtre, sans tabou.",
    "url": "https://www.youtube.com/@zeinebkhenissi",
    "followers": 73500,
    "engagement_rate": 0.0267,
    "avg_views": 34680,
    "bio": "Beauté, santé, esprit : je démonte les idées reçues avec humour, science et lucidité.\nBienvenue dans un espace où on soigne l’intelligence autant que la peau. الدكتورة خنيّسي. أكثر من ٢٥ عامًا في الطب ونظرة ناقدة لكل شيء.\nالجمال، الصحة، والعقل… أفكّك المسلّمات بعلم وجرأة وابتسامة.\nمرحبًا بك في مساحة نعالج فيها العقل كما نُعالج الجسد.\n\n",
    "recent_titles": [
      "#pourtoi #viralvideo#fyp",
      "#pourtoi#vitamin#healthylifestyle#viral",
      "#pourtoi #skincare #viralvideo#waxing#skin #aesthetic",
      "#pourtoi#cooking#kitten #viral",
      "#pourtoi #ai #trending #pourtoi",
      "#pourtoi #skincare #viralvideo# Botox",
      "#pourtoi # #viralvideo #adidas",
      "#pourtoi#adidas#running#athlete",
      "esthetique",
      "#pourtoi#guthealth#digestion # viral# health#doctor",
      "#pourtoi #skincare #viralvideo #live",
      "#pourtoi # mentalhealth # foryou #mentalhealthmatters"
    ]
  },
  {
    "handle": "@milamagnani",
    "external_id": "UCHwqT0YAc0lqqoQCQtEtloQ",
    "display_name": "mila",
    "url": "https://www.youtube.com/@milamagnani",
    "followers": 64000,
    "engagement_rate": 0.0111,
    "avg_views": 18954,
    "bio": "balancing life & my hormones\n",
    "recent_titles": [
      "letting my husband shave my face",
      "i'm moving to switzerland",
      "how i do my basic manicure",
      "doing nothing for the first time in years",
      "how i shave my entire PCOS body",
      "I have no one to invite to my wedding and that's ok",
      "trying to learn how to build a home within myself",
      "my non comedogenic makeup",
      "please don't make the mistakes i did",
      "i want to run away and live in a mountain",
      "reconnecting with my feminine energy",
      "my simple skincare routine that cleared my acne"
    ]
  },
  {
    "handle": "@pimplepoppingdaily8553",
    "external_id": "UCE8FBgmhnXu6QOHF6bR1tkg",
    "display_name": "Pimple Popping Daily",
    "url": "https://www.youtube.com/@pimplepoppingdaily8553",
    "followers": 21300,
    "engagement_rate": 0.0106,
    "avg_views": 13036,
    "bio": "acne 2021,\nblackheads 2021,\npimple popping,\nacne scars,\nacne treatment,\nhormonal acne,\nspironolactone acne,\nacne medication,\nchin acne,\nforehead acne,\ncomedonal acne,\nadult acne,\nsevere acne,\nacne face,\njawline acne,\nneck acne,\npustule acne,\nacne removal\n",
    "recent_titles": [
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K",
      "Pimple Popping & Blackheads 4K"
    ]
  },
  {
    "handle": "@jessicadiana",
    "external_id": "UCDUxmADw3fBinSXPaLTFBQQ",
    "display_name": "Jessica Diana",
    "url": "https://www.youtube.com/@jessicadiana",
    "followers": 13400,
    "engagement_rate": 0.0057,
    "avg_views": 1199,
    "bio": "A place to share my journey with PCOS, acne, weight gain, products / supplements and fitness. Follow me on Instagram : jessicaddiana  #cystersquad \n\nFor business inquires : [email removed] \n\nCreator of Cyster Squad Sweaters: www.jessicadiana.com\n\nLetter Club: PO Box 20107 Fairview PO, Vancouver BC",
    "recent_titles": [
      "14 OTHER Symptoms of PCOS (Not including the obvious)",
      "Getting back on track! Fixing acne breakouts, eating for PCOS, supplements!",
      "FIRST 5 STEPS after being diagnosed with PCOS!",
      "PCOS LIES OF THE WEEK!- Ep. 2",
      "PCOS and IMMUNITY",
      "5 PCOS DINNER IDEAS!- Easy and Cheap!",
      "BAD PCOS ADVICE!- Reaction Video",
      "What I eat in a day for PCOS+ Supplements I take",
      "5 FOODS I LIMIT WITH PCOS",
      "WHAT I EAT IN A DAY WITH PCOS",
      "TOP 5 MILKS FOR PCOS!",
      "Current Favourites!"
    ]
  },
  {
    "handle": "@heatherpcosprincess",
    "external_id": "UCPLpL31Vx0dei8ny9avNMlQ",
    "display_name": "Heather 𖤓 PCOS Princess",
    "url": "https://www.youtube.com/@heatherpcosprincess",
    "followers": 12200,
    "engagement_rate": 0.0023,
    "avg_views": 1554,
    "bio": "🎤Let’s become self-advocacy queens together\n🧑🏽‍🩰Lipedema Removal Orlando, FL\n🎀-121lbs Gluten/Dairy Free\n⬇️Embrace Your PCOS/PMOS Princess Era in 8 weeks!\n\n➡️Build your OWN PCOS Princess Routine👑: \n🔗 https://heatherpcosprincess.my.canva.site\n\n*My videos are for educational purposes only and not a substitute for medical advice. Please consult a doctor or registered dietitian before starting a new routine*\n\nCheck out my linktree for everything I use, my free community, my challenges, and more! \n\n🔗 https://linktr.ee/heatherpcosprincess",
    "recent_titles": [
      "My faja got a makeover 🥰",
      "POV your acne didn’t show up until… #pmos #pmosprincess #pcos #pcosprincess",
      "Sometimes the extra hair isn’t just your ethnicity #pcosprincess #hirsutism #pmos #pcosawareness",
      "I’m a PCOS, I’m sorry a PMOS Princess 👑 #pcosprincess #pcosawarenessmonth #pmosawarenessmonth #pmos",
      "I heard MLD doesn’t work after plastic surgery surgery? 🤔 #lipedema #lymphaticdrainage #massage",
      "4 week lipedema removal, breastlift, & torsoplasty update! #pcosprincess #lipedema #milamendpartner",
      "I just pulled “fishing line” from my body 😫",
      "Does PMOS or Lipedema make you itchier??",
      "3.5 Month Update Post Op Lower Body Lift | Lipedema Removal",
      "Honor My PMOS Cravings With Me After Surgery",
      "12 Days Post Op | No Pain Meds Again 😫 (Lipedema Removal & Upper Body Lift)",
      "Scars 8 Days PO Lipedema Removal | Upper Body Lift"
    ]
  },
  {
    "handle": "@naturopathicbeauty9507",
    "external_id": "UCJN1KKdBVz3lbP5am_hsTJg",
    "display_name": "Naturopathic Beauty | Women's Acne Expert",
    "url": "https://www.youtube.com/@naturopathicbeauty9507",
    "followers": 11000,
    "engagement_rate": 0.0004,
    "avg_views": 774,
    "bio": "🌱 Helping women 25+ clear acne at the root\nFor women who’ve tried everything & nothing works\n20+ yrs experience | Featured in US Weekly + more\nFinally clear your skin!\n",
    "recent_titles": [
      "Things your doctor should have told you about acne, but didn’t",
      "These acne symptoms are not normal",
      "Which insulin pattern is causing your acne and energy crashes?",
      "September 3, 2026",
      "The labs of a woman who stopped looking in the mirror because she hated her skin.",
      "10 weird signs that your acne is just about to clear.",
      "Your acne is always telling you something",
      "10 Normal lab results I don’t ignore if you have acne. ￼",
      "Here are 5 acne patterns I see most often as a Naturopathic Doctor",
      "You are not healing your acne because you still have gut issues",
      "Common symptoms you didn't know were related to acne",
      "Many women struggling with persistent acne also experienced symptoms like ￼"
    ]
  },
  {
    "handle": "@ahanabanerjee",
    "external_id": "UC-AZeJoX_pbPILSERkgUYaw",
    "display_name": "Ahana Banerjee",
    "url": "https://www.youtube.com/@ahanabanerjee",
    "followers": 5530,
    "engagement_rate": 0.0022,
    "avg_views": 1056,
    "bio": "I am a 26-year-old founder, Forbes 30 Under 30 technology honouree, Sunday Times Young Power List 2024 honouree, and physics grad from Imperial College London. My work has been featured by the likes of Sifted, Courier Magazine and EU-Startups, and I have been a speaker at numerous conferences and universities, including Oxford, Cambridge, Bocconi and IIT.\n\nMy company, Clear, is fuelling innovation for brands and empowering consumers in the skincare industry using data, technology and community. I was accepted to Y Combinator (W21) with the idea and subsequently raised ~$1M in venture funding for the company. We have been recognised for our beauty-tech innovation by L’Oréal and Beiersdorf, and were recognised by Apple under \"Best New Apps\" and \"App of the Day\" on the App Store.\n\nVisit Clear's website getclearapp.com, to download Clear for free on iOS & Android, and subscribe to my YouTube channel to follow my journey building Clear!\n",
    "recent_titles": [
      "I didn’t exceed my cumulative dosage #skincare #acne #dermatology #accutane",
      "first time in like 2 yrs that I’m on my period with ZERO active breakouts 🥹 #skincare #acne #derm",
      "this is how I get nhs prices for my acne meds #skincare #acne #dermatology",
      "Feels so good to be here again 🥹 #skincare #acne #dermatology",
      "these have been my spiro dosages #skincare #acne #dermatology",
      "Sry my hair is a little crazy but here’s my skin 9 months into spiro! #skincare #acne #dermatology",
      "This is how I get NHS prices for my acne medication prescription  #acne #dermatology ￼",
      "With the Clear app, you can get 10% off skindoc in the UK. #skincare #acne #accutane #dermatology",
      "This is why I didn’t use tret while on accutane #skincare #acne #accutane #dermatology",
      "Ultra close up of some pms breakouts 7 months into spironolactone #skincare #acne #dermatology",
      "I’ve increased my spiro dosage from when I started #skincare #acne #dermatology",
      "Another day, another skin check! 8 months on spironolactone now. #skincare #acne #dermatology"
    ]
  },
  {
    "handle": "@conquerpcos",
    "external_id": "UCrjTFl6vxxyS7E6UgO9tVPQ",
    "display_name": "Conquer PCOS",
    "url": "https://www.youtube.com/@conquerpcos",
    "followers": 4730,
    "engagement_rate": 0.0329,
    "avg_views": 45978,
    "bio": "Conquer PCOS is an Initiative by Metropolis Healthcare Ltd. \nConquer PCOS feature stories about PCOS warriors who have conquered PCOS and are leading healthy and happy lives with PCOS. Our channel is also committed to creating awareness about PCOS. It is estimated that about one in ten women in the reproductive age group suffers from PCOS. A lot of women and girls are diagnosed late because they do not have the correct information about the condition. ‘Conquer PCOS is an effort to spread awareness about this lesser-known condition and get more women diagnosed. Conquer PCOS is also aimed at women with PCOS and help them take control of their health and well-being.",
    "recent_titles": [
      "Why does Hirsutism occur in PCOS",
      "What causes Baldness in PCOS and treatment",
      "What are the treatment options available to manage Hirsutism in PCOS",
      "Skin Darkening or Pigmentation in PCOS",
      "Regular Skin Care Regimen in Acne   Skin Care Treatment  Important Tips",
      "PCOS Acne   What you need to know and treatment",
      "How to know if you have Hirsutism or just excessive body hair",
      "Five wonder food from kitchen for your PCOD",
      "Female Pattern Hair Loss in PCOS  Types of Alopecia",
      "Exercise and PCOD",
      "Does Diet help in Losing weight in PCOS 1",
      "Dietary Interventions in PCOD"
    ]
  },
  {
    "handle": "@sopuresab",
    "external_id": "UCrVNgPGc-8f8t0BhnLnfB9g",
    "display_name": "Sabrina",
    "url": "https://www.youtube.com/@sopuresab",
    "followers": 2080,
    "engagement_rate": 1.4471,
    "avg_views": 286104,
    "bio": "ig: sopuresab\nskin ig: pureskin.withsab\n",
    "recent_titles": [
      "GRWM | ABH RENAISSANCE PALETTE",
      "POST ACCUTANE | SKIN CARE ROUTINE",
      "MY ISOTRETINOIN (ACCUTANE) JOURNEY + BEFORE AND AFTER PHOTOS"
    ]
  },
  {
    "handle": "@acnefree",
    "external_id": "UCWiY11X3QxUA_usUTdgPb-A",
    "display_name": "AcneFree",
    "url": "https://www.youtube.com/@acnefree",
    "followers": 1700,
    "engagement_rate": 0.0206,
    "avg_views": 6457,
    "bio": "AcneFree offers a complete line of highly effective acne treatment products.",
    "recent_titles": [
      "Prom For Good With Chicago Hope Academy",
      "How To Use Therapeutic Sulfur Mask With Any Acne Skincare Routine | AcneFree",
      "How To Use Oil-Free Cleanser To Treat And Care For Acne-Prone Skin | AcneFree",
      "How To Use Adapalene Gel Acne Treatment In Your Skincare Routine | AcneFree",
      "How To Use Blackhead Removing Scrub Acne Treatment With Charcoal | AcneFree",
      "How To Use Sensitive Skin 24 Hour Clearing System For Sensitive Acne-Prone Skin | AcneFree",
      "How To Use Oil Free 24 Hour Acne 3-Step Clearing System To Get Rid Of Acne Fast | AcneFree",
      "How To Use Salicylic Acid Body Spray | Pore Clarifying Solution For Chest And Back | AcneFree",
      "How To Use Terminator 10 Severe Acne Spot Treatment To Clear Skin Fast | AcneFree",
      "How To Use Witch Hazel Mattifying Toner For Acne Prone Skin | AcneFree",
      "How To Use Severe Acne 24 Hour Clearing System To Treat Persistent Breakouts | AcneFree",
      "Affordable Dermatology-Inspired Acne Treatments for Clear Skin | AcneFree"
    ]
  },
  {
    "handle": "@functionalpcos",
    "external_id": "UCkpjczdswG75euZ4O5C7dgg",
    "display_name": "Functional PCOS | Amber Fischer MS CNS",
    "url": "https://www.youtube.com/@functionalpcos",
    "followers": 958,
    "engagement_rate": 0.0146,
    "avg_views": 1023,
    "bio": "Hi, I'm Amber Fischer, a functional nutritionist, Licensed Dietitian Nutritionist and Certified Nutrition Specialist (CNS) who works with PCOS and related hormone conditions.\n\nI create content for PCOS from a functional approach, helping you find the root of your symptoms and using food and lifestyle to make major changes to your health and quality of life. \n\nI have PCOS myself and have been in your shoes.  This work is my true passion and I'm so glad you're here!\n\nIf you're looking for a guide through nutrition changes for PCOS, consider one of my courses like PCOS Foundations or Functional PCOS, find more about them through my links or website.",
    "recent_titles": [
      "Matcha Latte Tutorial for PCOS | How to make matcha for PCOS",
      "How to stop insulin resistance in PCOS",
      "Insulin Resistance Smoothie Recipe Formula for PCOS",
      "How to Help PCOS Insulin Resistance Pt 2",
      "PCOS Low Carb Dinner",
      "Phases of Treating Insulin Resistance with Diet pt 1",
      "Two Phases of Fixing PCOS Insulin Resistance",
      "Soy and Phytoestrogens for PCOS- Is soy bad for pcos?",
      "PCOS Root Causes: Insulin Resistance",
      "3 Truths of PCOS Nutrition",
      "PCOS Insulin Resistance",
      "Insulin Resistant PCOS Signs and Symptoms"
    ]
  },
  {
    "handle": "@ashlynlanaville",
    "external_id": "UCzWLct6t-tYjqCW2qr7dYhw",
    "display_name": "Ashlyn Lanaville",
    "url": "https://www.youtube.com/@ashlynlanaville",
    "followers": 692,
    "engagement_rate": 0.0879,
    "avg_views": 4442,
    "bio": "Hey friends!\nWelcome to my YouTube channel! Here, I reveal all my tips and tricks to achieve clear skin and what my favorite products are from someone who has always had acne. Thanks for stopping by and don't forget to subscribe!\n",
    "recent_titles": [
      "REASONS WHY DIFFERIN GEL ISN'T WORKING | differin gel review 2021",
      "sunday day in my life: unpacking, cooking, creating etsy digitals, and working out",
      "THE BEST DIFFERIN GEL ROUTINE | Differin Gel Review 2021 + Differin Gel Tips",
      "i FINALLY have clear skin?! | 1 Month on Differin Gel and 6 Months on Spironolactone for Acne Update",
      "STARTING DIFFERIN AGAIN | How to Use Differin Gel, Updated Differin Gel Skincare Routine",
      "an update...",
      "2 Month Acne Update on Spironolactone | Is spironolactone even working??? | Spironolactone Update",
      "REASONS WHY YOU NEED TO START DIFFERIN GEL NOW | Differin Gel Review 2021, 1 Year on Differin Gel",
      "Skin Care Routine and My Current Favorites 2021 | Best Skincare Products that Actually Work 2021",
      "DID DOXYCYCLINE WORK??? | My Doxycycline Experience, Doxycycline for Acne Before and After Pictures",
      "My Skincare Update 2021 | Spironolactone for Acne, Accutane, POST Doxycycline",
      "HOW TO APPLY DIFFERIN/TRETINOIN"
    ]
  },
  {
    "handle": "@tori7894",
    "external_id": "UC9ccwVW0UA4KouRDKIgHEuw",
    "display_name": "Victoria Cervantes",
    "url": "https://www.youtube.com/@tori7894",
    "followers": 454,
    "engagement_rate": 0.4355,
    "avg_views": 11607,
    "bio": "",
    "recent_titles": [
      "Spironolactone before and after | 1 year update for hormonal acne",
      "How to treat acne from spironolactone purge | Spironolactone before and after | Products I used",
      "Laneige lip sleeping Mask | Korean beauty skincare | Most requested",
      "Nighttime Skincare Routine that cleared red marks | Tretinoin cream before and after",
      "Tretinoin Q&A | How I lightened the PIE (aka red marks) on my cheeks",
      "Current Favorties | Kawaii plushie | Nastygal sandals",
      "How I treat the PIE (aka red marks) on my cheeks | Tretinoin tips | Products I used",
      "Spironolactone before and after | How I cleared hormonal acne | Products I used + Clindamycin",
      "FOUNDATION ROUTINE | HOW TO COVER ACNE /SCARS | NARS SOFT MATTE FOUNDATION",
      "tori love Live Stream",
      "Wavy Hair Tutorial"
    ]
  },
  {
    "handle": "@honeydew-care",
    "external_id": "UCN1G_tbYRO1dHcv_GfPhOxA",
    "display_name": "Honeydew Care",
    "url": "https://www.youtube.com/@honeydew-care",
    "followers": 337,
    "engagement_rate": 0.0314,
    "avg_views": 915,
    "bio": "Smarter skincare prescribed for you.\n",
    "recent_titles": [
      "Isotretinoin with Persistent Acne",
      "TRT can ramp up oil production, and for some that means bigger breakouts 👀",
      "How to Manage the Isotretinoin Purge",
      "Hyperpigmentation 101 with our co-founder and Chief Medical Officer, Dr. Joel Spitz, MD",
      "Accutane Cumulative dose - broken down",
      "Body acne ≠ face acne... and treating it can look a little different. Here’s what to know 👀",
      "Cumulative dose can play a big role in your isotretinoin (Generic Accutane) treatment plan.",
      "TRT Induced Acne",
      "What is cumulative dose on Accutane? 👀",
      "Body Acne: What to Know",
      "The viral tretinoin + azelaic acid combo… in ONE cream 👀",
      "Should You Take Accutane with a Meal?"
    ]
  },
  {
    "handle": "@honestyforyourskin",
    "external_id": "UC54T6IzofGMGBk9-J6Qi-rQ",
    "display_name": "Acne Scientist | Cheryl Wooodman",
    "url": "https://www.youtube.com/@honestyforyourskin",
    "followers": 255,
    "engagement_rate": 0.0127,
    "avg_views": 130,
    "bio": "When nothing else works: science-backed acne healing that actually lasts\n\nI know what it's like to cancel plans because your skin's flared up again 😔 To avoid mirrors. To feel like you're the only person your age still dealing with this.\n\nI'm Cheryl - scientist 👩🏻‍🔬 award-winning skincare formulator, and former acne sufferer who got fed up with treatments that only worked temporarily. \n\nNow I help women get to the root cause of their acne 🌱 instead of just managing symptoms.\n\nOn my channel, you'll find:\n• The science behind why conventional treatments fail\n• What’s actually causing your breakouts 🔍\n• How to heal from the inside out ✨\n\nNo shame, no judgment, no miracle promises - just real talk and real solutions.\n\nIf you're ready to understand your body instead of fighting it, get started today by joining my free acne class - I'll help you identify your acne type and walk you through exactly what you need to do to heal naturally 👉 honestyforyourskin.co.uk/acneclass\n",
    "recent_titles": [
      "3 'Healthy' Habits That Made Her Hormonal Acne WORSE (Acne Warrior Review)",
      "How To Clear Hormonal Acne Naturally (Megan’s Acne Journey)",
      "How Do I Know If My Acne Is Hormonal? (5 Signs)",
      "Why Do I Have Acne If My Hormone Levels Are Normal? [Shock Science]",
      "I Ranked Every Benzoyl Peroxide Alternative (One Clearly Wins)",
      "PanOxyl vs Acnecide vs CeraVe: The BP Brand Battle",
      "Benzoyl Peroxide Vs Antibiotics for Acne: The Shocking Winner",
      "How I Finally Beat Hormonal Acne (My Honest Honesty For Your Skin Review)",
      "Benzoyl Peroxide Flare Up? STOP PUSHING THROUGH",
      "Why Benzoyl Peroxide Makes Your Skin Oily AND Dry (The Paradox)",
      "How To Use Benzoyl Peroxide WITHOUT Destroying Your Skin Barrier",
      "Watch This Before Layering Benzoyl Peroxide + Retinol"
    ]
  },
  {
    "handle": "@acneorgza",
    "external_id": "UCEWaTLA0jktEdMvC7vXGFaQ",
    "display_name": "Acneorgza",
    "url": "https://www.youtube.com/@acneorgza",
    "followers": 202,
    "engagement_rate": 0.0268,
    "avg_views": 412,
    "bio": "",
    "recent_titles": [
      "If you have dry skin - Try this! #acnecare #skincare #skincareroutine #dryskin #eczema",
      "Lucent Beauty and Skincare is stocking Acne.org.za products",
      "Mould and Acne: Could Kristin's Story Hold the Key? #acne #skincare",
      "Acne.org.za Hydrocolloid Pimple Patches - Invisible, Waterproof, Healing #skincare #acne",
      "Your Journey to Beautiful Skin with Angelique: A Step-by-Step Guide",
      "Unlock the Power of Micronised Benzoyl Peroxide: A Gentler, More Effective Acne Solution",
      "Managing hormonal acne - tips from a skincare expert",
      "The battle of adult acne - the hormonal war - but she's found her answer",
      "My mini skincare routine with Acne.org.za",
      "Clear Pores 101: Balancing Ingredients for Flawless Skin",
      "Breaking Beauty Standards: Embracing Acne-Prone Skin with Confidence #acne #skinhealing #skincare",
      "Stay hopeful and committed, no matter what your skin is doing 🤗 #love #acne #skincare"
    ]
  },
  {
    "handle": "@acneremovall",
    "external_id": "UCC2RDZUdRMZY31iSSfzzLYg",
    "display_name": "Acne Removal",
    "url": "https://www.youtube.com/@acneremovall",
    "followers": 199,
    "engagement_rate": 0.0884,
    "avg_views": 2376,
    "bio": "\n\nThis is new channel of Acne treatment Hương official\n🌼 Acne with traditional methods to help you have beautiful skin, quality prestige, we have our own treatments and traditional remedies\nHow to get blackheads and white heads, get rid of itchy toxic blood on the patient's face.\nBamboo tube absorbs all sebum and acne. They also work to make skin healthier and brighter, I have soaked herbs on bamboo tubes\n#neck acne#acnetreatmen#blackhead#にきび#acnetreatmentofficial#asmrpimplepopping #poppingpimple #pustulesextraction #papulesacne #cysticacnestory #bambootube #mụnẩn #nặnmụn #điềutrịmụn #mụnđầuđen #mụnđầutrắng #mụntrứngcá #HuongDaNang #sưng #tấy#拔粉刺#粉刺#做臉#にきびの治療",
    "recent_titles": [
      "Big Blackheads Cystic Acne Blackheads&Whiteheads Removal Pimple Popping #43",
      "Pimples popping big pimpole Removal #42",
      "Pimples popping big pimpole Removal #41",
      "Pimples popping big pimpole Removal #40",
      "Pimples popping big pimpole Removal #39",
      "Pimples popping big pimpole Removal #38",
      "Pimples popping big pimpole Removal #37",
      "Pimples popping big pimpole Removal #36",
      "Pimple popping gone worng #35",
      "Pimple popping gone worng #34",
      "Grossest Most Disgusting Pimples and Pops EVER",
      "HOW TO TREAT ACNE AT HOME acne All you need to know #33"
    ]
  },
  {
    "handle": "@catalily446",
    "external_id": "UCtfYlfZgXQYs8qVtdwIUoAg",
    "display_name": "catalily",
    "url": "https://www.youtube.com/@catalily446",
    "followers": 192,
    "engagement_rate": 0.2478,
    "avg_views": 9549,
    "bio": "Welcome Everyone!\nAt this point, these videos are just to help people decide whether they think Accutane is worth it or not. Hope everyone enjoys:)",
    "recent_titles": [
      "Going on Accutane Again?",
      "My Accutane Journey: 1 Month POST Accutane",
      "My Accutane Journey: 8 months on Accutane",
      "My Accutane Journey: 7 Months on Accutane",
      "My Accutane Journey: 5 months on Accutane",
      "Accutane Journey: 17 weeks on Accutane",
      "Accutane Journey: 14 weeks on Accutane",
      "Accutane Journey: 2 months on Accutane",
      "Accutane Journey: 6 weeks on Accutane",
      "Accutane Journey: 1 month on Accutane",
      "My Accutane Journey: Week 1 of Accutane",
      "Accutane Journey: 1 week before Accutane"
    ]
  },
  {
    "handle": "@care1141",
    "external_id": "UCXkhz6URR4YIuwYksDRL2Iw",
    "display_name": "care1141",
    "url": "https://www.youtube.com/@care1141",
    "followers": 159,
    "engagement_rate": 0.1378,
    "avg_views": 4638,
    "bio": "Lots of videos about beauty, acne, and random stuff; hopefully you can find something interesting. Subscribe if you like! I put up new videos randomly when I have an idea or get a request. Follow me on Twitter and Instagram, linked below!\n\n**Leave a comment with any video suggestions you have! \n\n**Email: [email removed]",
    "recent_titles": [
      "Spironolactone: Still my acne miracle? Answering your questions + 8 year update",
      "ULTA Giveaway Winner",
      "Proactiv Solution Review",
      "CLOSED ULTA Giveaway",
      "Summer Dress Look Book",
      "Get Ready With Me",
      "Tea Tree Oil For Acne",
      "Spironolactone Update",
      "Frizz-Ease 3 Day Straight Review",
      "Keep Compact Makeup From Caking",
      "Brazilian Blowout vs. Chi Enviro",
      "Personality Tag!"
    ]
  },
  {
    "handle": "@acneantiagingandproducts",
    "external_id": "UCzCL2d5e3Km7zIk1cWlRZyQ",
    "display_name": "Acne, Anti Aging, and Products",
    "url": "https://www.youtube.com/@acneantiagingandproducts",
    "followers": 125,
    "engagement_rate": 0.18,
    "avg_views": 2477,
    "bio": "Find skin care routines, product recommendations, and science based information for anti aging, acne, and other skin care concerns. We do our best to research ingredients and the medical research that backs them up. But just because we like it doesn't mean it will work for everyone! \n\nSign up for our sponsored newsletter at SkinCareJunkieReport.com and get weekly industry round-ups curated from top influencers and experts. \n\nFreebies:\nAcne: 7 day Meal Plan for the Acne Diet on https://skincaresumo.com/acne-diet/\n\nFind all our on socials @ https://skincaresumo.com/get-connected\n",
    "recent_titles": [
      "Adine Lustre - New Face of K Beauty Brand Barenbliss #skincare #kbeauty",
      "How To Get Rid of Dark Circles Under Your Eyes #skincare #health",
      "Is Sperm Good For Acne? And Better Ways To Get Clear Skin!",
      "Does Salt Water Help Acne? Myth vs Truth",
      "How To Make Salt Water For Acne | Natural Acne Skin Care Routine",
      "Does Salt Water Help Acne? How To Make a DIY Salt Spray",
      "How To Eat For Clear Skin - Acne Diet, Natural Acne Cure, Adult Acne!",
      "Sperm doesn't work for acne. But the Acne Diet does!",
      "Try the acne diet - it's easy, cheap, and yummy!",
      "Find out what else causes acne and what to eat instead",
      "Best Acne Diet Recipe! Mushrooms are an acne-fighting powerhouse!",
      "Don't eat high GI food... it causes acne"
    ]
  },
  {
    "handle": "@diaryofanigeriangirl",
    "external_id": "UCo5t6NfRnfJFZYMaVOvP-Eg",
    "display_name": "Mercy Bolufemi ",
    "url": "https://www.youtube.com/@diaryofanigeriangirl",
    "followers": 73,
    "engagement_rate": 0.0708,
    "avg_views": 140,
    "bio": "Hi Darling, welcome to my channel❤️\n\n✨No Niche content🥴 with a drizzle of Open Dialogue, Motherhood, Relationship, Lifestyle & Faith. \n✨Email: [email removed]\n\n\nMy goal is to make relatable content. I hope we get to connect more. \n",
    "recent_titles": [
      "Hormonal Acne Journey #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo #asmr",
      "Hormonal Acne Journey #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo #asmr",
      "Hormonal Acne Journey #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo #asmr",
      "Hormonal Acne Journey #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo #asmr",
      "Hormonal Acne Journey  #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo #asmr",
      "Hormonal Acne Journey #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo #asmr",
      "Capcut video editing for beginners",
      "Hormonal Acne Journey 🫶🏾🥹 #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo",
      "#exploring  #modestyfashion  #modesty #christian #dailyvlog #shorts #viral #viralvideo #hormonalacne",
      "Hormonal Acne Journey 🫶🏾🥹 #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo",
      "Hormonal Acne Journey 🫶🏾🥹 #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo",
      "Hormonal Acne Journey 🫶🏾🥹 #shorts #acne #acnejourney #acneprone #hormonalacne #viral #shortvideo"
    ]
  },
  {
    "handle": "@acneactivist1196",
    "external_id": "UCT5bXLQwJLOHVoyiwA2Vhfg",
    "display_name": "Acne Activist",
    "url": "https://www.youtube.com/@acneactivist1196",
    "followers": 49,
    "engagement_rate": 0.424,
    "avg_views": 498,
    "bio": "Welcome! Anne from The Acne Activist here, and I'm all about helping you IMPROVE your Acne with Nutrition.\n\nIt's not JUST acne tips... Sure, I've got in-depth videos about certain foods, whole foods, plant-based recipes, and a heap of hacks and scientific evidence to level up the quality of your skin. But what good is a great skin without a lot of FUN?!\n\nMy thoughts exactly. That's why I also cover a TON of Acne myths, challenges, how-to guides, lifestyle tips and other cool stuff to help you MAX OUT your results and get an amazing clear skin!\n\nSounding up your alley? Hit that SUBSCRIBE button and I'll see you in the comments!\n\n- ABOUT -\nI healed my (adult) acne after 20 years (!) by changing my diet. Studied Orthomolecular Nutritional Science at the Ortho Health Foundation in the Netherlands. I started Acne Activist + my instagram @acneactivist to spread this knowledge to a bigger audience and help people heal themselves and their skin.\n\n- FOLLOW ME -\ninstagram.com/acneactivist\n",
    "recent_titles": [
      "DIFFERENCE between ADULT and TEEN ACNE – What you NEED to know!",
      "Does VITAMIN C Help For ACNE? | Vitamin C and Acne Scars | Vitamin C in your Skincare Routine",
      "BIGGEST Mistakes I Made Struggling With Acne - Ask A Nutritionist",
      "Is FRUIT Bad For ACNE? | Does Fruit Cause Acne?",
      "ACNE MOTIVATION / INSPIRATION/ POSITIVITY - Ask A Nutritionist",
      "Is SOY Bad For ACNE? | Does Soy Cause Acne?",
      "The #1 QUICK FIX for ACNE! (It's Not What You Think!) | How to get RID of Acne FAST?!",
      "TOP 5 Foods to AVOID for Clear Skin - Ask A Nutritionist",
      "Does CHOCOLATE Cause Acne? (Yes, It Does!) - Chocolate Acne Relationship"
    ]
  },
  {
    "handle": "@bereglimmer",
    "external_id": "UCfOvWKAYucnz9Ot0b0wVPuw",
    "display_name": "Bere",
    "url": "https://www.youtube.com/@bereglimmer",
    "followers": 41,
    "engagement_rate": 0.2602,
    "avg_views": 1015,
    "bio": "My life through a camera \n\nInstagram : bereglimmer\nTiktok : bereglimmer \n\nBusiness Inquires 💌 [email removed] ",
    "recent_titles": [
      "Current Favorite Skincare Acne Edition",
      "#acneskin #hormonalacne #acne",
      "July 27, 2026",
      "July 24, 2026",
      "Acne ❤️‍🩹",
      "Cystic acne ❤️‍🩹",
      "Morning skincare on acne prone skin 💕  #acne #morningskincare #hormonalacne #acneskin #acnejourney",
      "Skincare on Cystic Hormonal Acne",
      "🥲 #hormonalacne #acne #acneskin",
      "Back acne 🤍",
      "🤍",
      "Grwm Acne Prone Makeup 🤍"
    ]
  },
  {
    "handle": "@mirandagray1207",
    "external_id": "UCCQwQgj-2kgFI4QUVD4uc6g",
    "display_name": "Miranda Gray",
    "url": "https://www.youtube.com/@mirandagray1207",
    "followers": 27,
    "engagement_rate": 0.6296,
    "avg_views": 323,
    "bio": "I’m on a mission to solve the underlying issue of my hormonal acne with the guidance of you guys, my followers. \n\nWe’re going to really get in to all the nooks and crannies of what is causing my acne through skin care, nutrition and gut health. \n\nFollow me along my journey as I find my confidence again and solve the issues to what is the cause of this horrible hormonal acne.",
    "recent_titles": [
      "SKIN UPDATE | WHAT I EAT IN A DAY VLOG",
      "HORMONAL ACNE! Who Am I? And What Is My Channel About?"
    ]
  },
  {
    "handle": "@shonieonaccutane",
    "external_id": "UCql_rPDxL2TSQbQfDQ00BDA",
    "display_name": "ShonieonAccutane",
    "url": "https://www.youtube.com/@shonieonaccutane",
    "followers": 23,
    "engagement_rate": 0.1976,
    "avg_views": 1747,
    "bio": "Sharing my experience with the acne medication \"Accutane\". I will be doing a video every week or every two weeks depending on signifigant changes in my skin. I'll  be talking about the changes in my skin, side effects from the medication and skin care routines for 6 months:). I hope these are really helpful for you! Always ask questions and PLEASE if you have any tips..share. :D",
    "recent_titles": [
      "Update on Accutane: Week 24 (Six Month) Finished?",
      "Foundation Recommendations: Before and During Accutane",
      "Update on Accutane: Week 16 (Fourth Month)",
      "Foundation Results Sneak Peak when on Accutane (Dry skin with acne)",
      "*HD* Update on Accutane: Week 14",
      "*HD* Update on Accutane: Week 12 (Third Month)",
      "Skincare Routine when on Accutane: I'm ACTUALLY washing my face in front of you!",
      "Update on Accutane: Week 8 (Two months)",
      "Update on Accutane: Week 4 + Physical Pill and Package of Medication",
      "Update on Accutane: Week 3",
      "Pre-Accutane"
    ]
  },
  {
    "handle": "@acnelabb",
    "external_id": "UCSKnufdvkRtdxeM0lUBkC4w",
    "display_name": "Acne-lab",
    "url": "https://www.youtube.com/@acnelabb",
    "followers": 21,
    "engagement_rate": 0.619,
    "avg_views": 85,
    "bio": "Clear skin starts with understanding your skin.\n\nOn this channel, we dive deep into acne what causes it, how different skin types react, and which routines and ingredients truly make a difference. Complex skin topics are broken down into simple, visual, easy-to-follow insights so you can make confident choices for your own skincare journey.\n\nNo myths. No overwhelm. Just clear, modern skin education designed to help you work with your skin, not against it.\n\nSubscribe and take the guesswork out of acne care.\n\n",
    "recent_titles": [
      "What Actually Causes Acne? Let’s Break It Down"
    ]
  },
  {
    "handle": "@xazkp",
    "external_id": "UCtec7W-Sbz5aBD34OEEZiXA",
    "display_name": "xazkp_",
    "url": "https://www.youtube.com/@xazkp",
    "followers": 7,
    "engagement_rate": 1.1429,
    "avg_views": 1228,
    "bio": "this channel is all about skincare beauty makeup. ✨️",
    "recent_titles": [
      "morning skincare routine to clear hormonal acne + comedonal acne + fungal acne #acneskincareroutine",
      "Why Your Skincare Suddenly Stopped Working #skincare #shorts #skincareshorts #skininfluencer",
      "how to make skincare routine | Skin Type vs Skin Concern | You're Choosing Skincare Wrong #skincare",
      "Is anua azelaic acid Making Your Skin Worse? #anua #azelaicacid #acneproneskin #acneserum #acne",
      "acne was painful 😢 #acnejourney #acnetreatment #acneproneskin #acneskincare #acnecare #acne",
      "Why Am I Suddenly Breaking Out? 9 Common Causes of Sudden Acne #Acne #AcneBreakout #AcneTreatment",
      "why acne keeps coming back | how to stop acne #day6 #acnes #acneclinic #acneproneskin",
      "DAY 5| Skin Purging vs Acne Breakout | How to Tell the Difference #acneproneskin #acnecare #skincare",
      "Is It Acne or Something Else? | Skin Conditions Mistaken for Acne 🤍#skincare #acne #rosacea #milia",
      "the truth about hormonal acne .. #acne #acneproneskin #acnecare #acnetreatment",
      "acne prone skin girlies. i also have been through this.. if u want help just comment me. #acne",
      "How to Clear Acne | 3 Acne Mistakes That Damage Your Skin Barrier #acne #acneproneskin #acneskincare"
    ]
  },
  {
    "handle": "@cleanspiracy",
    "external_id": "UCgo4iuEMSPqCo7OqFWSsv8A",
    "display_name": "Cleanspiracy",
    "url": "https://www.youtube.com/@cleanspiracy",
    "followers": 3,
    "engagement_rate": 0.9722,
    "avg_views": 1031,
    "bio": "💚 Welcome to Cleanspiracy, where we believe in gentle, honest, and effective skincare for everyone.\n\nStruggling with persistent acne on your face, back, chest, or shoulders? We understand. That's why we created our Swiss-made, dermatologist-tested Dual-Clear Acne Treatment Mist. Our science-backed, 99.54% natural origin formula is designed to treat breakouts on all skin types, including the most sensitive skin, without the harshness of traditional treatments.\n\nSubscribe for product showcases, skincare tips, and to learn how to build a simple routine that respects your skin's natural wisdom.\n\nReady to start your journey to clearer, calmer skin? Shop our collection below.\n\n➡️ Visit Our Website: https://cleanspiracy-beauty.com/\n\nhttps://www.instagram.com/cleanspiracy/\nhttps://pinterest.com/cleanspiracybeauty/\nhttps://www.facebook.com/CleanspiracySkincare\nhttps://soundcloud.com/skincareinsightsswiss\n",
    "recent_titles": [
      "How acne forms",
      "The best acne treatment out there",
      "How to get rid of chest acne 👇",
      "Healing from acne isn’t linear, but it is happening.",
      "5-Minute Bacne Routine",
      "Skincare must-have if you have acne-prone skin",
      "Here's why your acne doesn't go away",
      "Ever seen an acne mist with TWO layers?",
      "The one ingredient we can’t live without: Niacinamide",
      "Benefits of Green Tea for Acne-prone Skin",
      "Plot Twist: When Puberty Was Not The Finale",
      "Back Acne Routine"
    ]
  },
  {
    "handle": "@cysticacne9",
    "external_id": "UCF9gZUhdFme1cgavYjlaRDQ",
    "display_name": "Cystic Acne ( Acne Treatment )",
    "url": "https://www.youtube.com/@cysticacne9",
    "followers": 3,
    "engagement_rate": 0.25,
    "avg_views": 167,
    "bio": "",
    "recent_titles": [
      "acne cystic extraction | acne treatment | acne treatment video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatment video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatment video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatment video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatments video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne trentment video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | Blackhead removal | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatment video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatments video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatment video | satisfying acne removal on face",
      "acne cystic extraction | acne treatment | acne treatments video | satisfying acne removal",
      "acne cystic extraction | acne treatment | acne treatment video | satisfying acne removal on face"
    ]
  },
  {
    "handle": "@what_causes_acne",
    "external_id": "UCJTmhpe29HY0ENwKNIh7xVw",
    "display_name": "What Causes Acne",
    "url": "https://www.youtube.com/@what_causes_acne",
    "followers": 3,
    "engagement_rate": 0,
    "avg_views": 19,
    "bio": "What does everyone have in common? AH-ha!™ It’s Acne Hormones.\n\n\rIf you think you have hormonal acne or believe it’s just something that only affects adult females, think again! In\r fact, hormonal acne is just acne. All acne breakouts have a hormonal component—in all people of all genders and \rall ages!\r \n\nHow does it work? Hormones in the skin, known as androgens, increase at certain times throughout life,\r kickstarting the acne cycle.\r Understanding why your breakouts happen can help you understand how to treat and prevent acne. \n\nLearn what \rcauses adult and teen acne, get some skin care basics, understand acne hormones, and more in the videos on\rthis channel and at AcneHormones.com.",
    "recent_titles": [
      "Think You Shouldn’t Still Be Getting Acne in Your 40s? Dr. Pimple Popper Pops That Myth!",
      "Greasy Food Doesn’t Cause Greasy Skin and Acne Breakouts. Dr. Pimple Popper Explains Why",
      "How Do Different Types of Acne Treatments Work? Dr. Pimple Popper Breaks Down the Options",
      "Dr. Pimple Popper Gives Some Helpful Tips for Discussing Acne With Your Teen",
      "Sebum Is Part of the Acne Chain Reaction But it’s Not a Root Cause | Dr. Pimple Popper Talks Sebum",
      "The Stress and Acne Connection: Dr. Pimple Popper Explains How They’re Related (And How They’re Not)",
      "Dr. Pimple Popper Talks About Guys’ Acne and What Really Causes It. Hint: It’s Acne Hormones!",
      "Dr. Pimple Popper Talks to Caregivers About Why It’s Important for Teens to See a Dermatologist",
      "Dr. Pimple Popper Explains What Acne Hormones Are and Why They’re a Root Cause of Acne Breakouts",
      "How Do You Self-Care? Watch for Some Ideas Like Exercise, Skin Care, or Dealing With Your Acne",
      "When it Comes to Acne, You’re Not Alone | Danny Shares His Feelings About Breaking Out in His 30s",
      "Dana Shares Her Acne Journey, How It Affects Her Social Life, and How She’s Moving Forward"
    ]
  },
  {
    "handle": "@hormonalacnecure5775",
    "external_id": "UCaYZBbPAZRJqE5lBY2WU8tA",
    "display_name": "Hormonal Acne Cure",
    "url": "https://www.youtube.com/@hormonalacnecure5775",
    "followers": 2,
    "engagement_rate": 0.5,
    "avg_views": 18,
    "bio": "",
    "recent_titles": [
      "Why Saliva Testing is better than Blood Testing for checking your Hormones?",
      "Where Do You Start When You Have Hormonal Acne"
    ]
  },
  {
    "handle": "@pcoswellnessbyzoe",
    "external_id": "UCjuFTNBHPuh2_0HP4se57aQ",
    "display_name": "Zoë | PCOS & Hormonal Acne Specialist",
    "url": "https://www.youtube.com/@pcoswellnessbyzoe",
    "followers": 2,
    "engagement_rate": 1.8889,
    "avg_views": 168,
    "bio": "💫 I reversed my PCOS & acne naturally\n🎓 BSc Integrative Health | Holistic Nutritionist\n🛍️ Supplements that transformed my skin ⬇️\nPurevitalitybyzoe.com \n",
    "recent_titles": [
      "How I Cleared My Acne With PCOS",
      "The BEST Diet For PCOS (not keto or vegan)",
      "BRAND NEW PCOS RESEARCH APRIL 2025",
      "5 Simple Things You Should Do For PCOS",
      "Morning Routine for Healthy Hormone Balance",
      "3 MAJOR REASONS WHY YOU CANT LOSE WEIGHT",
      "THIS is giving you belly fat",
      "3 Drinks to Help Balance Your Hormones Naturally!",
      "The Hidden Signs of Chronic Stress & 3 Ways to Reduce it"
    ]
  },
  {
    "handle": "@acnequick4720",
    "external_id": "UCzGRuM12sSHh1Z1ecJ11tXg",
    "display_name": "Acne Quick",
    "url": "https://www.youtube.com/@acnequick4720",
    "followers": 0,
    "engagement_rate": null,
    "avg_views": 50,
    "bio": "Thanks for watching ........\n\n*******************************************\nhow to treat acne,how to get rid of acne,how to cure acne,acne treatment,acne scars,get rid of acne,hormonal acne,acne skin care,what is acne,acne skincare,dermatologist acne,acne treatments,best acne treatment,skin care,acne removal,causes of acne,what causes acne,acne skincare routine,acne scarring,acne diet,pimple,how to treat acne at home,acne causing foods,acne home remedies,stop acne,acne scar,fungal acne,acne help,skincare,skin,acne prone skin,adult acne,dermatology,zit,cyst,dermatologist,how to get rid of acne scars,how to remove acne scars,acne scar removal,acne scar treatment,best acne face wash,honey for acne,cystic acne treatment,whitehead,pimple popping,cystic acne,acne cure,dr pimple popper,blackhead,how to treat acne naturally,why do acne occur,acne treatment natural,why do acne develop,why do acne happen,how acne develop,acne treat ment,best treatment for acne,best products for acne,",
    "recent_titles": [
      "How To Treat Acne Get rid of Best acne treatment Skin care #15",
      "How To Treat Acne Get rid of Best acne treatment Skin care #14",
      "How To Treat Acne Get rid of Best acne treatment Skin care #13",
      "How To Treat Acne Get rid of Best acne treatment Skin care #12",
      "How To Treat Acne Get rid of Best acne treatment Skin care #11",
      "How To Treat Acne Get rid of Best acne treatment Skin care #10",
      "How To Treat Acne Get rid of Best acne treatment Skin care #09",
      "How To Treat Acne Get rid of Best acne treatment Skin care #08",
      "How To Treat Acne Get rid of Best acne treatment Skin care #07",
      "How To Treat Acne Get rid of Best acne treatment Skin care #06",
      "How To Treat Acne Get rid of Best acne treatment Skin care #05",
      "How To Treat Acne Get rid of Best acne treatment Skin care #04"
    ]
  }
];
