/**
 * Snapshot of the live YouTube pull (CLAUDE.md §12), written by `pnpm discover` on 2026-09-17.
 * The seed loads these as Seeded rows; they flip to Live only when the running build re-fetches them.
 * Public professional-account data only. Do not edit by hand; re-run `pnpm discover`.
 */
export type YoutubeSnapshotRow = {
  handle: string;
  external_id: string;
  display_name: string;
  url: string;
  followers: number;
  engagement_rate: number | null;
  avg_views: number | null;
  bio: string;
  recent_titles: string[];
};

export const YOUTUBE_SNAPSHOT: YoutubeSnapshotRow[] = [
  {
    "handle": "@drpimplepopper",
    "external_id": "UCgrsF4TYwmrV0QsXb8AoeHQ",
    "display_name": "Dr. Pimple Popper",
    "url": "https://www.youtube.com/@drpimplepopper",
    "followers": 9130000,
    "engagement_rate": 0.0008,
    "avg_views": 581260,
    "bio": "Welcome to the world of Dr. Pimple Popper, the one and only Sandra Lee, MD! As a board certified dermatologist, skin cancer surgeon, and cosmetic surgeon, I am a highly sought-after  expert in the field of dermatology. \n\nOn this channel, you'll find a treasure trove of videos that offer a window into my world. \nHopefully you'll learn about various skin conditions, hair  and nail issues, and cutting-edge cosmetic surgery techniques. Whether you're struggling with  blackheads, acne, cysts, warts, or looking for Botox, fillers, or liposuction, you'll find helpful advice and information here. \n\nBut this channel isn't just about skin care - it's about the amazing people I encounter every day.  You'll get to know some of my incredible patients and their stories, and maybe even fall in love  with dermatology just as much as I have! \n\n",
    "recent_titles": [
      "What is Steatocystoma Multiplex? | Dr. Pimple Popper vs. Steatocystomas",
      "One Patient. 4 Steatocystoma Sessions. | Dr. Pimple Popper",
      "Big Blackheads On The Nose Can Be Caused By Rosacea?",
      "It was a slippery little guy...⁠ Watch both procedures at the link ✌️❤️💥⁠",
      "Back Blackhead Cleanup ✌️❤️💥",
      "Two of my most famous Dilated Pores of Winer. Are one of these your fave, #popaholics?⁠",
      "Who knew that having a furrowed brow could be an advantage??⁠⁠",
      "Dr. Pimple Popper vs. The Uncomfortable, Inguinal Lipoma",
      "Consider this your reminder to give your ears a little skincare love, too. 💛⁠",
      "What do you think? 👽",
      "What is a Dilated Pore of Winer (and how do you prevent it?)",
      "Two Cysts on Two Different Temples 👉💥👈"
    ]
  },
  {
    "handle": "@doctorly",
    "external_id": "UCHCZnC9akNA9pBP7aJGNKdg",
    "display_name": "Doctorly",
    "url": "https://www.youtube.com/@doctorly",
    "followers": 3580000,
    "engagement_rate": 0.0007,
    "avg_views": 150282,
    "bio": "Evidenced-based skin care, dermatology, and medicine. Channel run by double Board-Certified Dermatologists with the goal of providing accurate, up-to-date information to our subscribers with full transparency. Thank you for following along with us. - Dr. Shah and Dr. Maxfield\n",
    "recent_titles": [
      "Aging Gracefully: What 5 YEARS Have Taught Us About Our Skincare",
      "Treat Itchy Fingers FAST: Dyshidrotic Eczema",
      "Derms LOVE Viral Tretinoin & Azelaic Acid Routine | Doctorly #shorts",
      "GLASS SKIN? Tretinoin & Azelaic Acid Viral Routine Debunked",
      "Introducing the Doctorly Games | Doctorly #shorts",
      "Stop WASTING Money on Skincare | Doctorly #shorts",
      "THIS is Hydration",
      "Laser vs LED vs Microcurrent: Which Anti-Aging Device Actually Works?",
      "You're Spending WAY Too Much on Skincare",
      "Puffy Eyes? Try This | Doctorly #shorts",
      "We Put Dermatology Residents to the Test for $60,000 | Introducing Doctorly Games",
      "Where to start your skincare?"
    ]
  },
  {
    "handle": "@erikadiane",
    "external_id": "UCiU62OZdeYaOWzryECkxROA",
    "display_name": "Erika Diane",
    "url": "https://www.youtube.com/@erikadiane",
    "followers": 1710000,
    "engagement_rate": 0.0042,
    "avg_views": 220521,
    "bio": "hi! my name is Erika and i’m a girl who loves documenting my life✿ₒ✧º∿\ni typically share vlog-style content relating to everyday life, fashion, wellness, beauty, mental health, and more.\n\nSUBSCRIBE to keep in touch :)\n\nfor business inquiries/PR contact: [email removed]",
    "recent_titles": [
      "a few days in my life: camping + first day of school🌳🏫💗",
      "let’s catch up 🎀 relationship status, moving out, sad girl summer & more",
      "i had to move back…unpacking, organizing and settling back in at home🏡💗",
      "our “perfect” nyc sisters trip! shopping, food, and exploring the city🗽🛍️🥐🌷",
      "day in my life as a 20 year old with too much free time",
      "APARTMENT DIARIES🤸🏻🌸🪴decor updates, shopping, new routines + ikea adventures",
      "i went on my little sister’s senior beach trip…",
      "MOVING OUT FOR THE FIRST TIME",
      "my REAL wellness routine🧘🏼‍♀️🥝 (what I eat, workouts + mental health)",
      "GETTING OUT OF A WINTER SLUMP🌱🧺💕",
      "my last day being a teenager.",
      "SHOPPING AND DECORATING FOR CHRISTMAS🎄🎀 🛒  *ft my sister*"
    ]
  },
  {
    "handle": "@zelihaakpinar",
    "external_id": "UChME7blpRpX1ViN-oPBpNmw",
    "display_name": "Zeliha Akpinar",
    "url": "https://www.youtube.com/@zelihaakpinar",
    "followers": 1520000,
    "engagement_rate": 0.0232,
    "avg_views": 1436285,
    "bio": "Glad you're here :) Currently a Medical Doctor in the UK. Productivity, helpful content and memories are why I'm here... Lots of love 🤍\n\n📸Instagram\n@emz_akpinar\n\n📩Business enquiries\n[email removed]",
    "recent_titles": [
      "My Final Day in Oxford with my Doctor Coworker",
      "Comparing all 3 of my DJI cameras!! #djipocket4p #vlogcamera #pocketcamera",
      "Lazy Cleaning day with DJI ROMO P 🧹",
      "I Went Out for Food with my Doctor Coworker...",
      "My Last Day at Work and Escaping to Oxford",
      "Trip to Canary Islands shot on  DJI Osmo Pocket 4!🏝️🇮🇨🌺",
      "Living Alone vlog | 5am gym, rejection at work, getting back on track",
      "How I fake having a cameraman 😙",
      "productive weekend with me ft @insta360 GO Ultra Vlog Cam ⭐️",
      "Living Alone vlog | 5am grocery shop, new monitor, meeting neighbours",
      "Day in my life as a Doctor in my 20s | Full-Time in the UK",
      "72 hours in London | Christmas market, visiting sister"
    ]
  },
  {
    "handle": "@drkhaledsadek",
    "external_id": "UC1uQSMobq0kPWSrLz4dc49g",
    "display_name": "Dr Khaled Sadek",
    "url": "https://www.youtube.com/@drkhaledsadek",
    "followers": 1190000,
    "engagement_rate": 0.004,
    "avg_views": 207325,
    "bio": "Dr Khaled Sadek provides surgical and non-surgical cosmetic work: focusing on cyst and lipoma removal. He is also experienced in anti-wrinkle facial injections, in addition to being a London based GP. His clinics are located in Chelsea London. \n\nDr Khaled Sadek\n295 Kings Road\nChelsea\nLondon\nSW3 5EP\n\nwww.lipomacyst.com\n\n[phone removed] \n[email removed]",
    "recent_titles": [
      "Before and after #cystremoval #drkhaledsadek LIPOMACYST.com",
      "Better out the name #cystremoval #drkhaledsadek",
      "Dr Khaled explains what happens when leave cyst for too long| hair loss scarring disfiguration ￼",
      "Dr Khaled explains #cystremoval #drkhaledsadek",
      "Help is not too far away LipomaCyst.com with Dr Khaled Sadek #cystremoval",
      "Milking the cyst on the daily #cystremoval #cystremoval dr Khaled sadek",
      "Full video cyst #cystremoval #blackhead #drkhaledsadek",
      "Before & After #cystremoval dr Khaled Sadek LipomaCyst.com",
      "#cystremoval Dr Khaled Sadek with LipomaCyst.Com",
      "Massive scalp cyst removal #cystremoval #drkhaledsadek",
      "Full video #cystremoval dr khaled sadek",
      "Skin cyst removal in London LipomaCyst.com dr khaled sadek"
    ]
  },
  {
    "handle": "@labmuffinbeautyscience",
    "external_id": "UCg6P323bLV4zMSWFqFhvWMg",
    "display_name": "Lab Muffin Beauty Science",
    "url": "https://www.youtube.com/@labmuffinbeautyscience",
    "followers": 861000,
    "engagement_rate": 0.0023,
    "avg_views": 33381,
    "bio": "I’m Michelle, a science educator and chemistry PhD from Sydney, Australia. I’m here to help you work out which beauty products are worth buying and which aren’t, using science!\n\nI started Lab Muffin because I was frustrated that there weren't enough easy-to-understand explanations of the science behind beauty products. I firmly believe that anyone can understand the science behind skincare and beauty.\n\nFor business/PR enquiries: [email removed]\n\nDISCLAIMER: I am not a medical doctor. Care has been taken to ensure the accuracy of the information here, but it is provided for education and research purposes only and is not intended to be a substitute for professional medical advice, diagnosis or treatment. Always seek the advice of a qualified health provider regarding any medical conditions. No liability is accepted for any injury, loss or damage incurred by use of or reliance on the information provided by me.",
    "recent_titles": [
      "Naturopath vs chemist: endocrine disruptors in sunscreen",
      "Dry shampoo is toxic??",
      "AI companies won't make their products safer",
      "Moisturiser isn't working anymore? (ad)",
      "Why AI chatbots are bad at science",
      "The \"paid testimonial ban\" isn't just about paid ads",
      "This law might be making skin cancer worse",
      "AD What is Melasyl? @LOrealParisAU Melasyl Creamy Serum #skincare #lorealparis #melasyl",
      "Sunscreens and other skincare I've been enjoying (Clarins ad)",
      "AD There are lots of myths around which actives you can and can’t layer - let’s do some debunking!",
      "Beware of lash serums!",
      "Fragrances are toxic?"
    ]
  },
  {
    "handle": "@acnetreatmenthuongdanang",
    "external_id": "UCViR3aeehZPMnx9w49DhJPw",
    "display_name": "Acne treatment Hương Đà Nẵng",
    "url": "https://www.youtube.com/@acnetreatmenthuongdanang",
    "followers": 706000,
    "engagement_rate": 0.0031,
    "avg_views": 184497,
    "bio": "This is new channel of \"Acne treatment Hương official\".\nPlease subscribe my new channel to watch latest videos.\nGuide how to get acne cores, get effective acne but not swollen, attractive and high technology level.\n\nFanPage: Hương Trị Mụn\nTel: [phone removed]\nAddress: Trần Thị Diễm Hương, 7 Mộc Bài 1 Street, Liên Chiểu District, Đà Nẵng City, Việt Nam (Tel: [phone removed])\n[Facebook]\nhttps://www.facebook.com/diemhuongs200279\nhttps://www.facebook.com/acnetreatmenthuong\n[website]\nhttps://www.acnehuong.com/\nOld channel: http://www.youtube.com/c/AcnetreatmentHươngofficial\nEmail: [email removed]\n\n=====================================\n#Hương Đà Nẵng #acne treatment #Hương official #acne removal #inflammatory \n#skin care #hidden acne #pimple #scar removal #whitehead\n#blackheads #blackhead extraction #whiteheads extraction #poping\n#putules #papules #cysts #pimple popper blackhead #bamboo tube\n#mụn #nặn mụn #điều trị mụn #spa #chăm sóc da #mụn sẩ",
    "recent_titles": [
      "Acne Treatment Huong Da Nan#member#short#Coming soon",
      "Acne Treatment Huong Da Nang#752#Huong's staff_ Blackheads Long time no see.",
      "Acne Treatment Huong Da Nang# 022 | 2023",
      "Acne Treatment Huong Da Nang# membership 010 |  | 2023",
      "Acne Treatment Huong Da Nang# 038 |  Loyal fans Mai Part 1",
      "Acne Treatment Huong Da Nang#750#Huong's staff_ Balckheads",
      "Acne Treatment Huong Da Nang#749#Huong's staff_ Balckheads",
      "Acne Treatment Huong Da Nang#746#Huong's staff_ Part2 Blackheads and inflammation TET Holiday",
      "Acne Treatment Huong Da Nang#748#Huong's staff_ Part1 Blackheads and inflammation TET Holiday",
      "Acne Treatment Huong Da Nang#750#Happy New Year, TET Holiday",
      "Acne Treatment Huong Da Nang#746#Huong's staff_ Blackheads appear on the skin.",
      "Acne Treatment Huong Da Nang#746#Huong's staff_ Blackheads that have dried out can be removed easily"
    ]
  },
  {
    "handle": "@loannguyenacnetreatment",
    "external_id": "UCxeYxrANL3oMEBZfyHIolxQ",
    "display_name": "Loan Nguyen Acne Treatment",
    "url": "https://www.youtube.com/@loannguyenacnetreatment",
    "followers": 693000,
    "engagement_rate": 0.0006,
    "avg_views": 26600,
    "bio": "-Loan Nguyen Acne Treatment chuyên đăng các video về lấy nhân mụn to, độc và lạ mắt nhất cho các bạn thích xem nặn mụn_specializing in posting videos about getting big, poisonous and fancy acne for you who want to see squeezing acne\n-Loan Nguyen  Acne Treatment còn giúp cho người xem thư giản cho những người thích xem nặn mụn_Also helps viewers relax for those who like to see pimple\n-Cảm ơn các bạn đã xem video của Loan Nguyen Acne Treatment_Thank you for watching the video of Loan Nguyen Acne Treatment\n-Hãy đăng kí theo dõi( Please subscribe): http://pesc.pw/LWQXN\n\n-Nội Dung Hay Và Hữu ích hãy ũng hộ tác giả tại ( Good and Useful Content, please support the author at)\n-Hoạc đơn giản chỉ cần like , share là động lực để tôi làm nhiều video chất lượng và hấp dẫn hơn (Or simply like, share is the motivation for me to make more quality and attractive videos)\n  -Loan Nguyen Acne Treatment THANK YOU.\n➡ Call/Zalo:            ",
    "recent_titles": [
      "Loan Nguyen Acne Treatment 2vv",
      "Loan Nguyen Acne Treatment 1vv",
      "Loan Nguyen Acne Treatment 016cc",
      "Loan Nguyen Acne Treatment 015cc",
      "Loan Nguyen Acne Treatment 014cc",
      "Loan Nguyen Acne Treatment 013cc",
      "Loan Nguyen Acne Treatment 012cc",
      "Loan Nguyen Acne Treatment 011cc",
      "Loan Nguyen Acne Treatment 04cc",
      "Loan Nguyen Acne Treatment 03cc",
      "Loan Nguyen Acne Treatment 02cc",
      "Loan Nguyen Acne Treatment x"
    ]
  },
  {
    "handle": "@anythinggoeswithemma",
    "external_id": "UCJvR4zNAPRJoMDF3A912dBA",
    "display_name": "anything goes with emma chamberlain",
    "url": "https://www.youtube.com/@anythinggoeswithemma",
    "followers": 531000,
    "engagement_rate": 0.0039,
    "avg_views": 72195,
    "bio": "anything goes podcast with emma chamberlain\nnew episodes every thursday\nlisten anywhere you listen to podcasts\nwatch on spotify and youtube\ninstagram @anythinggoes\ntiktok @anythinggoes\n",
    "recent_titles": [
      "bittersweet",
      "what a relief to not keep secrets!!",
      "its time to have a conversation with them",
      "friendship breakups and boundaries, advice session",
      "its what makes us who we are today",
      "what im struggling with",
      "growing is so uncomfortable lol",
      "its not about not caring",
      "we should all wear our heart on our sleeve",
      "the detachment rabbit hole",
      "youve got to close one door to open another",
      "even if you know better, its still there"
    ]
  },
  {
    "handle": "@amicharlizex",
    "external_id": "UCIX1edrhZBJfzz5zrkBknZQ",
    "display_name": "Ami Charlize",
    "url": "https://www.youtube.com/@amicharlizex",
    "followers": 432000,
    "engagement_rate": 0.0019,
    "avg_views": 42138,
    "bio": "Vlogs, Travel, Beauty, Fashion & Lifestyle !!",
    "recent_titles": [
      "hair food was calling… so obviously I answered  #GarnierHairFood #ad",
      "MOVING IN WITH MY BOYFRIEND AT 19! 🏡",
      "paris to london | girls trip + about time we catch up!",
      "Ad Finally sharing my secret to my glass hair ✨",
      "SPEND MY 19TH BIRTHDAY WITH ME + what i got! 🎂",
      "girls trip to a villa in cyprus for my 19th birthday, this is what happened...",
      "run errands w me and prepping for a girls holiday!!",
      "Flying to NEW YORK CITY alone at 18 because a brand invited me?!",
      "GRWM for date night: hair, make up & outfit transformation",
      "trying to get (and keep) my life together tbh",
      "SPENDING ON MY DADS CARD UNTIL HE CATCHES ME! 😳",
      "i fear this was too honest… 😭"
    ]
  },
  {
    "handle": "@nipunkapur",
    "external_id": "UClcYchlRF3XUbkxL0u1GCvQ",
    "display_name": "Nipun Kapur ",
    "url": "https://www.youtube.com/@nipunkapur",
    "followers": 408000,
    "engagement_rate": 0.016,
    "avg_views": 188792,
    "bio": "Hello Hello & Welcome to Skincare Simplified. \nI am a certified skincare consultant & coach and I design skincare routines. I am here to help you find your way through the thousands of skincare products available and find your ideal routine.\nSubscribe for daily skincare videos and \nJoin my membership to access member only live streams where I speak with you one on one and help you design your skincare routine.\nhttps://www.youtube.com/@NipunKapur/membership\n",
    "recent_titles": [
      "Ranking viral Medicube products #viralkorean #skincare #medicubeskincare",
      "How to shave your face correctly #faceshaving #shaving #bestrazorforwomen",
      "How to get rid of dull tanned face? #facetan #dullskin",
      "Is dr Althea cream really worth it? Review of Dr Althea skincare #345cream #147cream #dralthea",
      "How to treat pigmentation at home | Best serum for pigmentation in India | melasma skincare India",
      "HAIRFALL versus hair breakage #hair #hairfall #hairgrowth",
      "How to get rid of intense body tan? #tanremoval #bodytan #bodycare",
      "Best haircare products in India for hair growth #hairoil #heatprotection #antihairfall",
      "Which is the best Kajal in India? I check 10 but will recommend only 3 #makeup #beauty #kajal",
      "How to treat dark inner things and intimate areas safely at home. #intimatearea #pigmentation",
      "How to choose the right sunscreen for summer #skincare #deconstructsunscreen #sunscreen",
      "How to choose the right vitamin C ? #vitamincserum"
    ]
  },
  {
    "handle": "@acnetreatmentmaingocchannel93",
    "external_id": "UCiXH9DPHCys9HQCkIJZuQfQ",
    "display_name": "Acne Treatment Mai Ngoc Channel Official",
    "url": "https://www.youtube.com/@acnetreatmentmaingocchannel93",
    "followers": 389000,
    "engagement_rate": 0.002,
    "avg_views": 31370,
    "bio": " ACNE TREATMENTS  CHANEL\n#spa #maingoc #maingocspa #acne #acnetreatment #acnetreatmentmaingoc #maingocoffical #Bambootubeacnetreatment\n",
    "recent_titles": [
      "Pimple treatment video - Acne Treatments Mai Ngoc 💕💕💕",
      "ONE ACNE - Acne Treatments Mai Ngoc 💕💕💕",
      "ONE ACNE - acne treatment Mai Ngoc #điềutrịmụnđànẵng #acne #acnetreatment #trending",
      "Removing subcutaneous acne - Acne Treatments Mai Ngoc 💕💕💕",
      "Acne Treatment Mai Ngoc #điềutrịmụnđànẵng #pimple #acne #topgamedoithuonguytin",
      "White bumps under the skin - Acne Treatments Mai Ngoc 💕💕💕",
      "Little Familly ❤️ #điềutrịmụnđànẵng #acne #pimple #blackheads #emcobanglongvequemecunganh",
      "Massive amounts of Blackheads  p1 - Acne Treatments Mai Ngoc 💕💕💕",
      "Massive amounts of Blackheads - Acne Treatment Mai Ngoc #điềutrịmụnđànẵng #acne #blackheads  #pimple",
      "Acne Treatment Mai Ngoc #điềutrịmụnđànẵng #pimple #acne #blackheads #acnetreatments",
      "Remove clotted blood from the mouth area - Acne Treatments Mai Ngoc 💕💕💕",
      "Acne whiteheads treatment - Acne Treatments Mai Ngoc 💕💕💕"
    ]
  },
  {
    "handle": "@theacnechannel",
    "external_id": "UCLfpBAyfXl_2VTMigDlGonA",
    "display_name": "THE ACNE CHANNEL",
    "url": "https://www.youtube.com/@theacnechannel",
    "followers": 258000,
    "engagement_rate": 0,
    "avg_views": 564,
    "bio": "The Acne Channel is #1 Acne Resource on YouTube. Here we talk all about Acne and Acne Scarring! \n\nSubscribe to see our new weekly uploads. Comment to see what video we should create next! \n\nThe Acne Channel was founded by Daisy Jing, @daiserz89 in 2009 where she documented her journey with Acne. Daisy shared her vulnerability with having Acne and shared not only the physical and emotional pain she had while dealing with acne. She launched Banish (http://www.banish.com) after her experience with acne and credits the success of Banish to this channel.  Since then, we've opened the Acne Channel to other content creators to share their expertise with Acne and Acne Scarring. However, the vision of the original channel: Vulnerability, Authenticity, and Trustworthy reviews have always been the main values of this channel.\n\nThis channel does not accept sponsorships and does not earn affiliate commissions\n",
    "recent_titles": [
      "Money can buy a lot of things, but can't buy this",
      "Microneedling Mistakes That Can Make Your Skin Worse",
      "Microneedling Can Go Wrong. Here’s What You Need to Know.",
      "We all know that one person that judges like this #ACNE",
      "I Found Raw Footage of Me From 2017 | The Mission Behind Banish",
      "I'm taking matters into my own hands #acnescars",
      "At-Home Microneedling 101: What Beginners Need to Know",
      "Why I Stopped Chasing Perfect Skin | My Acne Scar Journey",
      "How Deep Should You Really Microneedle?",
      "Not all baddies can do it.. so I had to take it into my own hands #acne",
      "10 Things I Wish I Knew Before Getting Acne",
      "Microneedling: What needle size is the best? #acnescars #microneedling"
    ]
  },
  {
    "handle": "@glowjournalmamata",
    "external_id": "UC1yejTEJ4V5GKmWr7y5U8ug",
    "display_name": "Glow Journal Mamata",
    "url": "https://www.youtube.com/@glowjournalmamata",
    "followers": 186000,
    "engagement_rate": 0.0023,
    "avg_views": 15907,
    "bio": "Real skin. Real stories. From cystic acne struggles to skincare wins, I’m sharing every step, product test, and hard-earned tip to help you love the skin you’re in. 💛\n\n📨Collab: [email removed]",
    "recent_titles": [
      "For anyone dealing with active acne AND the marks at the same time, this is how I layer",
      "this is how I cope 😭 Not sponsored",
      "Not the day I wanted my skin to choose violence 😭",
      "Obsessed ♥️#hairtransformation #redhair #cherryredhair #hairtransition #hairdye",
      "Suddenly very grateful my acne is on my face 😭 Anyway, I love you acne. Please leave.",
      "All credit goes to Mum 😂 My only contribution was the hair. I’m learning the tutorial with you guys",
      "My sister asked for “a few things” and apparently I heard take half the house 😭",
      "My skin has officially become a rental property and apparently nobody is paying rent. 😭",
      "Manifesting clear skin using reverse psychology. 😭#acneproneskin #adultacne #acnehumor",
      "My acne is breaking out AND my skin is peeling, so I’m fighting the urge to throw everything at it.",
      "Box dye had absolutely no business turning out this good 😭🍒",
      "First day of tretinoin"
    ]
  },
  {
    "handle": "@hanaspaclinic",
    "external_id": "UCsqem1_c1PHlqKPu-1hW_Hg",
    "display_name": "HANA Spa - Clinic",
    "url": "https://www.youtube.com/@hanaspaclinic",
    "followers": 176000,
    "engagement_rate": 0.0581,
    "avg_views": 2030597,
    "bio": "HANA Spa & Clinic  TRỊ MỤN - XÓA MỜ THÂM\n- 𝘉𝘢̣𝘯 𝘵𝘳𝘢𝘰 𝘵𝘰̂𝘪 𝘯𝘪𝘦̂̀𝘮 𝘵𝘪𝘯 - 𝘵𝘰̂𝘪 𝘵𝘳𝘢𝘰 𝘣𝘢̣𝘯 𝘴𝘢̆́𝘤 đ𝘦̣𝘱 -\nĐịa chỉ: 479/22 Phan Văn Trị, P.5, Q. Gò Vấp (đối diện Emart)\nHotline [phone removed] (Zalo)\nFacebook: HANA Spa & Clinic \n(https://www.facebook.com/hana.trimun.xoamotham)\n",
    "recent_titles": [
      "Hana #79: A young boy had blackheads for years",
      "Hana #78: A blackheads field",
      "Hana #77: A poor boy but don't worry, my boy",
      "Hana #76: Another guy has severe inflammation",
      "Hana #75: The guy's facial skin is seriously infected",
      "HANA #74: AN AWESOME BLACKHEADS FIELD",
      "Enjoy Your Day with HANA Spa - Clinic #73",
      "Enjoy Your Day with HANA Spa - Clinic #72",
      "Enjoy Your Day with HANA Spa - Clinic #71",
      "Enjoy Your Day with HANA Spa - Clinic #70",
      "Enjoy Your Day with HANA Spa - Clinic #69",
      "Enjoy Your Day with HANA Spa   Clinic #68"
    ]
  },
  {
    "handle": "@teamacne",
    "external_id": "UCcDbXrS6z1Eu633Ot3nsGgA",
    "display_name": "Team Acne",
    "url": "https://www.youtube.com/@teamacne",
    "followers": 138000,
    "engagement_rate": 0.0009,
    "avg_views": 3717,
    "bio": "Welcome everyone to the official Team Acne YouTube group! A place where we can all share, get to know each other and express ourselves without fear of judgement! I wanted to make this group so we can really build a group feeling!  I will be sharing information, personal experience and content on how to improve your confidence and self esteem while still having acne!\n\nInstagram: http://www.instagram.com/TeamAcne\nMy recommended products: http://www.TeamAcne.com\nMy acne program: http://www.TheAcneMethod.com\n\nFacebook: Team Acne Instagram: teamacne",
    "recent_titles": [
      "Never Do THIS After Dermastamping",
      "The BEST Way to Shrink Large Pores (Nobody Talks About This)",
      "Skip Accutane. This ONE Vitamin Clears Acne.",
      "Your Acne Isn't a Skin Problem (It's a Gut Problem)",
      "EXACTLY what I’d tell myself before I cleared my acne #acne #acnepositivity #skincare",
      "Acne scars are TOUGH 🥲 Here’s whats helped mine! 😊 #acnescars",
      "The 7 Foods That Clear Acne (FROM EXPERIENCE)",
      "The BEST Way To Get Rid of Acne Scars (FROM EXPERIENCE)",
      "You Don’t Have Acne. You Have THIS!",
      "Retinoids and sunblock are GEMS for acne scars and…Banish! 🔥 use code BRIAN5  #acne #acnescars",
      "Which At Home Microneedling Device Is BEST?",
      "POV: you DON’T pop a pimple 😮😅 Could you? #pimple #acne"
    ]
  },
  {
    "handle": "@acnetreatmenthuongofficial",
    "external_id": "UC4MNOamHO1Bb0EW3QgOkgRw",
    "display_name": "Acne treatment Hương official",
    "url": "https://www.youtube.com/@acnetreatmenthuongofficial",
    "followers": 118000,
    "engagement_rate": 0.0263,
    "avg_views": 307399,
    "bio": "Hướng dẫn cách lấy nhân mụn, lấy nhân mụn hiệu quả không sưng, hấp dẫn, kỹ thuật cao.\nNew youtube channel: https://www.youtube.com/channel/UCQrSQJJJZTbgwuJkGi8XfIQ\nFanPage: Hương Trị Mụn\n  https://www.facebook.com/acnetreatmenthuong/\nFacebook:\n  https://www.facebook.com/diemhuongs200279",
    "recent_titles": [
      "ACne Treatment Huong official",
      "Relax with Acne Treatment Huong official # 004",
      "Enjoy Your Day with Acne treatment Huong official",
      "Acne Treatment Huong official",
      "Get inflamed acne for the boy",
      "[ Acne treatment Hương official ] Clean blackheads for lady",
      "[ Acne hide ] Hidden acne because use wrong drug",
      "[ Acne treatment Hương official ] Treating hidden acne, bran acne",
      "[ Blackhead ] get blackheads for young sister",
      "[ whiteheads ] Get your acne name Hoang ( official video )",
      "Acne pea | get pustules clean  ( Official Video )",
      "Acne treatment Hương beauty | My new channel"
    ]
  },
  {
    "handle": "@harshitadave",
    "external_id": "UCk9jTMVlPPZ0MyePgW5BzDQ",
    "display_name": "Harshita Dave",
    "url": "https://www.youtube.com/@harshitadave",
    "followers": 75500,
    "engagement_rate": 0.1809,
    "avg_views": 665429,
    "bio": "Chillin' and creatin' ✨",
    "recent_titles": [
      "Adult acne is so hard to deal with 😭 #shortsaday #acne #clearskin #relatable #trending #acnejourney",
      "Spend a day with me on the sets of Crime Patrol 🎬 #minivlog  #shootlife #crimepatrol #actor",
      "Is BTS Jungkook following me? 🫣👀😍 #shortsaday #btsjungkook #btsarmy #relatable #funny #bts",
      "People with acne can relate 🥲 #shortsaday #acne #acneskin #relatable #acneproneskin #pimplepatch",
      "Nykaa Sale Haul 👀🛍️ #shortsaday #nykaahaul #tirahaul #beautyhaul #nykaasale #makeuphaul",
      "Tira & Nykaa Sale Haul 👀🛍️🤑 #shortsaday #tirahaul #nykaahaul #beautyhaul #skincare #kbeauty",
      "My Health Update! I need to talk about this #shortsaday #healthupdate #hyperthyroidism #anemia",
      "STORYTIME: Our New House Was A NIGHTMARE. We Took Legal Action",
      "Our SOCIETY ran out of WATER 😭 | First Airbnb Experience + Honest Review",
      "People who get it, get it! #shortsaday #acnejourney #acneproneskin #relatable #acnefighter #acne",
      "It gets better ❤️‍🩹 #acnejourney #shortsaday #acnetreatment #acneproneskin #clearskin #acnescars",
      "My brother is in a movie with Huma Qureshi 😱😍 #shortsaday #minivlog #babydodiedo #moviescreening"
    ]
  },
  {
    "handle": "@brookealexandrah",
    "external_id": "UC80mE_lfymobuSixDcInHEw",
    "display_name": "Brooke Alexandra",
    "url": "https://www.youtube.com/@brookealexandrah",
    "followers": 70900,
    "engagement_rate": 0.0007,
    "avg_views": 2600,
    "bio": "holistic health + acne healing\ntiktok @brookealexandrah\n\nemail: [email removed]\n",
    "recent_titles": [
      "doctor LAUGHS at acne patient #acne #shorts",
      "trying new skincare with ACNE PRONE skin #shorts #acne",
      "I cleared my acne after EIGHT years #acne #shorts",
      "the BEST shampoo for acne prone skin #acne",
      "the high protein breakfast that BALANCED my cortisol and helped CLEAR my acne #hormonebalance",
      "the hormonal acne journey. #hormonalacne #skincare #shorts",
      "KEY SUPPLEMENT FOR STRESS & ACNE #acne #stress #shorts",
      "Why is this the GO TO acne treatment?! #shorts #acnetreatment",
      "WHY ACNE COMES BACK #shorts #acne",
      "acne diets are OUT of control #acne #diets",
      "proof you can have clear skin & NEVER restrict certain foods #shorts",
      "My skin transformation. #shorts #holistichealth"
    ]
  },
  {
    "handle": "@milamagnani",
    "external_id": "UCHwqT0YAc0lqqoQCQtEtloQ",
    "display_name": "mila",
    "url": "https://www.youtube.com/@milamagnani",
    "followers": 64000,
    "engagement_rate": 0.0111,
    "avg_views": 18959,
    "bio": "balancing life & my hormones\n",
    "recent_titles": [
      "letting my husband shave my face",
      "i'm moving to switzerland",
      "how i do my basic manicure",
      "doing nothing for the first time in years",
      "how i shave my entire PCOS body",
      "I have no one to invite to my wedding and that's ok",
      "trying to learn how to build a home within myself",
      "my non comedogenic makeup",
      "please don't make the mistakes i did",
      "i want to run away and live in a mountain",
      "reconnecting with my feminine energy",
      "my simple skincare routine that cleared my acne"
    ]
  },
  {
    "handle": "@danacneorg",
    "external_id": "UC_vdkBmxbKUQ7ffoP011wPw",
    "display_name": "Acne.org",
    "url": "https://www.youtube.com/@danacneorg",
    "followers": 43800,
    "engagement_rate": 0.1159,
    "avg_views": 362724,
    "bio": "Home of The Regimen, which has gotten millions of people completely clear. Acne.org is a community-based site with the latest information on all things acne. We also have product reviews and forums. You guys also asked me to make products for The Regimen, so I did that for you everyone, and they are available at DanielKern.org.",
    "recent_titles": [
      "What Is Acne? Crash Course.",
      "Using glycolic acid to help clear acne - Acne.org",
      "The Acne.org Regimen - Acne Treatment - Official Instructions",
      "Latest diet and acne research as of Feb. 7, 2014",
      "Taking Accutane with a high fat meal - important for absorption",
      "Drugs and acne",
      "How to pop a pimple - Instructions from Acne.org",
      "How to shave - Instructions from Acne.org",
      "The Acne.org Regimen Step 3: Moisturizer",
      "Checking in - the stuff I'm researching right now",
      "Applying Acne.org Benzoyl Peroxide on The Acne.org Regimen",
      "Attaching a Gillette Trac II Plus cartridge"
    ]
  },
  {
    "handle": "@sadhavicollection",
    "external_id": "UC9Zg4ql-G70E5bxBqIsodTg",
    "display_name": "sadhavi collection",
    "url": "https://www.youtube.com/@sadhavicollection",
    "followers": 33800,
    "engagement_rate": 0.0012,
    "avg_views": 4796,
    "bio": "sadhavi collectionis for branded cloths with affortable price range . \n\nDisclaimer:you can choose fashion and love youself life is beautiful with new cloths with new vibe. ",
    "recent_titles": [
      "sadhavi collection is live!booking number [phone removed] ",
      "ಗೋವಾ ಬೀಚ್ ❤️❤️",
      "hogenakalla falls 😊",
      "flood in bengalore",
      "nature",
      "aztec clay ನಿಮ್ಮ ಎಲ್ಲ ಸ್ಕೀನ್ problems ಗೆ ಯೂಸ್ ಮಾಡಿ 100% works",
      "skin shine cream side effects ಇಂದ ಹೊರಗಡೆ ಬರಲು ಸರಳ ಉಪಾಯ ಇಲ್ಲಿದೆ",
      "tranexamic acid serum for pimple marks dark spots",
      "kaff chimney Review ಕನ್ನಡ",
      "fungal acne( ಪಂಗಲ acne ಗೆ ಒಂದು ಒಳ್ಳೆ cream ಇಲ್ಲಿದೆ)",
      "Azelaic acid 10 % cream review ಕನ್ನಡ",
      "BIOTIQUE Moisturizer review ಕನ್ನಡ (ಬಯೋಟೆಕ್ moisturizer review)"
    ]
  },
  {
    "handle": "@holisticcareclinic",
    "external_id": "UCdGT26o-stjoQL-uQDV3IEw",
    "display_name": "Holistic Care",
    "url": "https://www.youtube.com/@holisticcareclinic",
    "followers": 20500,
    "engagement_rate": 0.0002,
    "avg_views": 402,
    "bio": "INSTAGRAM: https://www.instagram.com/holisticare...\nFACEBOOK: https://www.facebook.com/holisticare.pk\nWEBSITE: https://holisticare.pk/",
    "recent_titles": [
      "#weightloss",
      "#skincare",
      "#pcos",
      "#backpainrelief",
      "#skincare",
      "#dental",
      "#skincare",
      "#dietplan",
      "#skincare",
      "#autism #adhd",
      "#kneepain",
      "#skincare"
    ]
  },
  {
    "handle": "@alenamarib",
    "external_id": "UCbZgU4pdByaKvTCSiKjUUyw",
    "display_name": "Alenamari",
    "url": "https://www.youtube.com/@alenamarib",
    "followers": 20400,
    "engagement_rate": 0.0425,
    "avg_views": 45744,
    "bio": "Hi, ich bin Alena 🫶🏼\n\nGelernte Kosmetikerin mit einer langen Akne Geschichte, crazy Cat Lady und first time mom, die mit einer Prise Feminismus und einem Hauch Sarkasmus dir fundiertes Wissen über SkinCare, Akne, Skinpicking, PCOS und Makeup vermittelt 💕\nKlingt cool? Dann bleib gerne hier ☀️\n\n_________________________________________\n\nAnfragen per Mail an:\n[email removed]\n\nImpressum:\nhttps://sites.google.com/view/alenamari-impressum/startseite",
    "recent_titles": [
      "wie findet ihr das Ergebnis?#overnightblowout #overnightcurl",
      "Ergebnis Mikroneedling Pickelpatches",
      "S.O.S. Methode gegen unterirdische Pickel#pickel #akne #pickelpatches #acneproneskin",
      "Makeup bei Akne? Ja, ja und nochmal ja 🫶🏼#akne #pickel #makeup #skinpicking #acnemakeup",
      "ich will nicht mehr auf Morgen warten.#selbstliebe #abnehmen #postpartum",
      "mit 30 Jahren immer noch Akne",
      "🤡 als ob ich kein Spiegel Zuhause hsbe",
      "Wie ihr ernähre mein Baby?!??",
      "Skincare routine",
      "after Birth body",
      "Grenzen setzen",
      "ZinkSalbe gegen Akne 🫣"
    ]
  },
  {
    "handle": "@jessicadiana",
    "external_id": "UCDUxmADw3fBinSXPaLTFBQQ",
    "display_name": "Jessica Diana",
    "url": "https://www.youtube.com/@jessicadiana",
    "followers": 13400,
    "engagement_rate": 0.0057,
    "avg_views": 1199,
    "bio": "A place to share my journey with PCOS, acne, weight gain, products / supplements and fitness. Follow me on Instagram : jessicaddiana  #cystersquad \n\nFor business inquires : [email removed] \n\nCreator of Cyster Squad Sweaters: www.jessicadiana.com\n\nLetter Club: PO Box 20107 Fairview PO, Vancouver BC",
    "recent_titles": [
      "14 OTHER Symptoms of PCOS (Not including the obvious)",
      "Getting back on track! Fixing acne breakouts, eating for PCOS, supplements!",
      "FIRST 5 STEPS after being diagnosed with PCOS!",
      "PCOS LIES OF THE WEEK!- Ep. 2",
      "PCOS and IMMUNITY",
      "5 PCOS DINNER IDEAS!- Easy and Cheap!",
      "BAD PCOS ADVICE!- Reaction Video",
      "What I eat in a day for PCOS+ Supplements I take",
      "5 FOODS I LIMIT WITH PCOS",
      "WHAT I EAT IN A DAY WITH PCOS",
      "TOP 5 MILKS FOR PCOS!",
      "Current Favourites!"
    ]
  },
  {
    "handle": "@naturopathicbeauty9507",
    "external_id": "UCJN1KKdBVz3lbP5am_hsTJg",
    "display_name": "Naturopathic Beauty | Women's Acne Expert",
    "url": "https://www.youtube.com/@naturopathicbeauty9507",
    "followers": 11000,
    "engagement_rate": 0.0004,
    "avg_views": 781,
    "bio": "🌱 Helping women 25+ clear acne at the root\nFor women who’ve tried everything & nothing works\n20+ yrs experience | Featured in US Weekly + more\nFinally clear your skin!\n",
    "recent_titles": [
      "Things your doctor should have told you about acne, but didn’t",
      "These acne symptoms are not normal",
      "Which insulin pattern is causing your acne and energy crashes?",
      "September 3, 2026",
      "The labs of a woman who stopped looking in the mirror because she hated her skin.",
      "10 weird signs that your acne is just about to clear.",
      "Your acne is always telling you something",
      "10 Normal lab results I don’t ignore if you have acne. ￼",
      "Here are 5 acne patterns I see most often as a Naturopathic Doctor",
      "You are not healing your acne because you still have gut issues",
      "Common symptoms you didn't know were related to acne",
      "Many women struggling with persistent acne also experienced symptoms like ￼"
    ]
  },
  {
    "handle": "@agelessglowchronicles",
    "external_id": "UCBz6_uLQNd7MeRkCqIFPexg",
    "display_name": "Ageless Glow Chronicles",
    "url": "https://www.youtube.com/@agelessglowchronicles",
    "followers": 9750,
    "engagement_rate": 0.0012,
    "avg_views": 479,
    "bio": "Skincare for brown skin that’s aging — without the hype.\nI’m Neha, a Creator in my 40s focused on well-aging through barrier health, pigmentation control, texture refinement, and collagen support. I test skincare long enough to see real changes — not overnight impressions. I break down ingredients, connect them to research, and show you how they perform in real routines.\nIf you’re 35+ navigating adult acne, hyperpigmentation, pore changes, and early signs of aging — this space is for you.\nNo miracle claims. No panic anti-aging.\nJust structured, honest skincare testing for real life.\n\n👉 Dermalogica certified for foundational understanding in treating melanin-rich skin.\n👉 ICA-certified skincare consultant, helping you understand why your skincare stops working — and how to fix it.\n",
    "recent_titles": [
      "HOW TO REPAIR YOUR SKIN BARRIER IN ONE WEEK !",
      "Eucerin Sun Protector Fluid SPF 50+ Review: Lightweight Hydration #shorts #skincare #sunscreen #spf",
      "Fix Your Skin Barrier for Clearer Skin #shorts #skinbarrier #skincare #barrierrepair",
      "5 Things You Do Daily That Destroy Your Skin Barrier (Brown Skin Edition)| Dermatologist Explains",
      "LED Count vs. Efficacy: What Really Matters? #shorts #skincare #LEDmask #brownskin",
      "Glycolic Acid: The Truth About Breakouts & Skin Types #shorts #skincare #brownskin #antiaging",
      "Glycolic Acid AHA Serum: Use it Carefully #shorts #skincare #brownskin #antiaging",
      "Omnilux vs CurrentBody LED Mask - Which One Should You Buy?",
      "Listen To Your Skin: The Ultimate Product Test #shorts #skincare #skincaremistakes #brownskin",
      "Skincare Routine: Adapt to Your Climate & Life #shorts #skincare #brownskin #skincareroutine",
      "Retinol Secrets: Patience is Key for Amazing Skin #shorts",
      "Retinol for Beginners: Avoid This Common Mistake! #shorts #retinol #skincare #brownskin"
    ]
  },
  {
    "handle": "@pimplespa1",
    "external_id": "UC8Pg3Tlt8CxlQbMCkBS4zFg",
    "display_name": "Pimple Spa",
    "url": "https://www.youtube.com/@pimplespa1",
    "followers": 8850,
    "engagement_rate": 0.0484,
    "avg_views": 30292,
    "bio": "Pimple Spa – Where Every Skin Has a Story\nAt Pimple Spa, we don’t just pop pimples – we restore confidence, one pore at a time. Led by experienced skincare professionals, our videos show the real, raw, and satisfying world of pimple extractions, acne care, and facial therapy. Whether you're curious about blackheads, acne, cysts, milia, or just love the satisfaction of a clean extraction – you'll find your skin-loving home here.\nBut more than skin, this channel is about people.\nEach face we treat carries a story – of pain, healing, and self-love. And we’re here to tell it all.\n🔔 Subscribe to Pimple Spa and join our mission to bring clear skin, calm minds, and confident smiles to people everywhere.\n\n#blackheads  #acne  #blackheadremoval  #pimplepopping  #pimple  #acnetreatment  #blackheadswhiteheads   #skincare  \n",
    "recent_titles": [
      "Satisfying Face Pimple Popping in Real Time - Massive Acne Removal Compilation Part 1",
      "ULTIMATE Satisfying Forehead Blackhead Removal – Deep Extraction",
      "Brutal Deep Nose Pimple Popping — Dermatologist Real Time",
      "Extreme Deep Acne Squeezing – Satisfying Blackhead Removal",
      "Deep Hidden Cheek Pimples Satisfying Blackhead Removal",
      "Extreme Nose & Cheek Pimple Popping – Satisfying Deep Extraction ASMR",
      "SATISFYING Forehead & Cheek Acne Treatment – Extreme Blackhead Removal ASMR",
      "Extreme Nose Blackhead Removal with Tweezers — Satisfying ASMR!",
      "Hidden Deep Blackheads EXPLODE with Pus – Satisfying Forehead acne  Extraction",
      "Deep Chin Pore Extraction – Satisfying Whitehead Removal ASMR",
      "SATISFYING Whitehead Removal ASMR -  Deep Pore Extraction",
      "Gentle Blackhead Popping Elderly Face Treatment"
    ]
  },
  {
    "handle": "@pathofast",
    "external_id": "UCFWC626RkgP5FxUjabmqZ6w",
    "display_name": "Pathofast Lab Pune | HIV, Semen, Home Blood Test",
    "url": "https://www.youtube.com/@pathofast",
    "followers": 7950,
    "engagement_rate": 0.0002,
    "avg_views": 169,
    "bio": "Pathofast is a pathology lab and Diagnostic center in Pune. We offer home sample collection services, and over 600+ tests include Semen test, HIV test/STD Testing, Vitamin D test, Vitamin B12 test, Dengue Test, LFT Test,CBC, Urine and Stool Tests in all parts of Pune City, with free home sample collection. Home Blood test in Pune is offered in the following areas : Blood Test in Aundh | Blood Test in  Baner | Blood Test in  Bavdhan |Blood Test in  Chinchwad | Blood Test in Dhanori | Blood Test in Hadapsar | Blood Test in Hinjewadi | Blood Test in Kalyani Nagar | Blood Test in Karve Nagar | Blood Test in Kharadi | Blood Test in Kondhwa | Blood Test in Koregaon Park |Blood Test in  Kothrud |Blood Test in  Magarpatta | Nigdi | Blood Test in Pashan | Blood Test in Sinhagad Road | Blood Test in Talegaon | Blood Test in Undri | Blood Test in Viman Nagar | Blood Test in Wakad | Warje |Blood Test in  Camp\n",
    "recent_titles": [
      "TSH टेस्ट क्या है? #thyroid",
      "Low TSH Level Meaning, Symptoms, Explained",
      "Low Vitamin D Symptoms, Meaning Explained",
      "Low B12 Symptoms, Meaning Explained",
      "Urine Glucose Positive Means | Urine Sugar Trace, 1+, 2+, 3+, 4+",
      "What is Black Urine : Causes, Symptoms & Is it dangerous?",
      "High Vitamin D3 Symptoms, Meaning, Explained",
      "Urine Routine Test (R/M) : Meaning, Report Sections, Symptoms | Complete Urine Examination (CUE)",
      "Lab Tests before Isotretinoin | Lab Tests before taking acne medicines",
      "Blood Tests Before Mounjaro | Lab Tests for patients taking Tirzapetide",
      "Top 5 signs of PCOD - You must know!",
      "Lab Tests before Surgery Explained | Pre-Operative Tests : Why They Matter & What They Mean"
    ]
  },
  {
    "handle": "@conquerpcos",
    "external_id": "UCrjTFl6vxxyS7E6UgO9tVPQ",
    "display_name": "Conquer PCOS",
    "url": "https://www.youtube.com/@conquerpcos",
    "followers": 4730,
    "engagement_rate": 0.0329,
    "avg_views": 45978,
    "bio": "Conquer PCOS is an Initiative by Metropolis Healthcare Ltd. \nConquer PCOS feature stories about PCOS warriors who have conquered PCOS and are leading healthy and happy lives with PCOS. Our channel is also committed to creating awareness about PCOS. It is estimated that about one in ten women in the reproductive age group suffers from PCOS. A lot of women and girls are diagnosed late because they do not have the correct information about the condition. ‘Conquer PCOS is an effort to spread awareness about this lesser-known condition and get more women diagnosed. Conquer PCOS is also aimed at women with PCOS and help them take control of their health and well-being.",
    "recent_titles": [
      "Why does Hirsutism occur in PCOS",
      "What causes Baldness in PCOS and treatment",
      "What are the treatment options available to manage Hirsutism in PCOS",
      "Skin Darkening or Pigmentation in PCOS",
      "Regular Skin Care Regimen in Acne   Skin Care Treatment  Important Tips",
      "PCOS Acne   What you need to know and treatment",
      "How to know if you have Hirsutism or just excessive body hair",
      "Five wonder food from kitchen for your PCOD",
      "Female Pattern Hair Loss in PCOS  Types of Alopecia",
      "Exercise and PCOD",
      "Does Diet help in Losing weight in PCOS 1",
      "Dietary Interventions in PCOD"
    ]
  },
  {
    "handle": "@exposedskincare",
    "external_id": "UCiEi9RJbvjc0PTMyYKcQAIg",
    "display_name": "Exposed Skin Care",
    "url": "https://www.youtube.com/@exposedskincare",
    "followers": 3060,
    "engagement_rate": 0.0019,
    "avg_views": 52190,
    "bio": "Exposed Skin Care is the best acne treatment combining Advanced Acne Science with Soothing Natural Extracts.  Exposed is guaranteed to give you clearer, healthier skin within 30 days or your money back.",
    "recent_titles": [
      "3-Step Acne Skincare Routine — Morning & Night | Exposed Skin Care",
      "Real results for clear skin.",
      "Hanz talks about Exposed Skin Care",
      "Haley's journey to clean acne-free skin.",
      "Exposed Skin Care with Hailey",
      "Hailey and Exposed Skin Care",
      "Exposed Skin Care and Gabriela",
      "Exposed Skin Care with Gabriela",
      "Gabriela's battle with acne.",
      "Gabriela and Exposed Skin Care",
      "Exposed Skin Care",
      "Exposed Skin Care"
    ]
  },
  {
    "handle": "@keepitclearpodcast",
    "external_id": "UCORhmDNrX-1x2s8KLKfoM6Q",
    "display_name": "Keep It Clear Podcast",
    "url": "https://www.youtube.com/@keepitclearpodcast",
    "followers": 2080,
    "engagement_rate": 0.0009,
    "avg_views": 250,
    "bio": "✨ Welcome to the Keep It Clear Podcast! ✨\n\nKeep It Clear (formerly The Clear Skin Chronicles) - The #1 Nutrition Pod on Apple\n\nIn a world that makes women’s health way too complicated, this podcast is all about simplicity. Clear skin, clear body, clear mind, clear life.\n\nRegistered Holistic Nutritionists and acne experts Katie Stewart and Cris Brown share how to cut through the noise and actually understand what your skin and body need. You’ll get practical tips, inspiring stories, and expert advice on everything from acne and hormones to digestion, stress, and self-care.\n\nBecause clear isn’t just about your skin. It’s about feeling confident, balanced, and aligned in every part of your health.\n\nTune in and let’s Keep It Clear. 💜\n\nWebsite: katiestewartwellness.com\nInstagram: @katiestewartwellness\n\nNew episodes every week. Subscribe and come hang out with us!\n",
    "recent_titles": [
      "Should Men Try a Period Cramp Simulator?",
      "Why Your Magnesium Blood Test May Be Misleading",
      "Healing Takes the Time It Takes",
      "Functional Labs for Acne: Why Your \"Normal\" Blood Work Isn't Telling You the Whole Story",
      "The Only Compliment That Actually Matters",
      "If They Dodge Questions Like a Politician, Run",
      "Nervous System First: Why Protocols Fail with Dylan Gemelli",
      "The One Vitamin You Can't Buy: \"Vitamin G\"",
      "The Gut Test Pattern We Keep Seeing in Acne Clients",
      "The Unexpected Souce of E. coli: Hospitals… or a Pet Raccoon",
      "The Most Valuable Health Advice: Stop Sharing Drinks & Forks",
      "What Hundreds of Gut Tests Told Us About Your Acne"
    ]
  },
  {
    "handle": "@mindspark-s6k",
    "external_id": "UCZa0b2YN5sUFqYtkHcLnkpA",
    "display_name": "MindSpark",
    "url": "https://www.youtube.com/@mindspark-s6k",
    "followers": 1800,
    "engagement_rate": 0.0053,
    "avg_views": 640,
    "bio": "",
    "recent_titles": [
      "He Lived 94 Years With a Bullet in His Head 😳",
      "This Animal Can Survive 18 Minutes Without Oxygen 😳",
      "An Animal With 3 Hearts and Blue Blood 🐙",
      "Why Does Your Brain Need 20% of Your Body’s Energy? 🧠⚡",
      "There’s a Planet Where It Rains Glass 🪐😳#space #planet #science #universe #facts #astronomy #shorts",
      "🌌 What Would Happen If You Fell Into a Black Hole? #Astronomy #Universe",
      "⚡ Why Do We See Lightning Before We Hear Thunder? #ScienceFacts #Lightning #Thunder #WeatherFacts",
      "Why Do You Forget Your Dreams So Quickly? 🧠💭",
      "What happens to your brain when you close your eyes 🧠👀 #sleep #education"
    ]
  },
  {
    "handle": "@acnefree",
    "external_id": "UCWiY11X3QxUA_usUTdgPb-A",
    "display_name": "AcneFree",
    "url": "https://www.youtube.com/@acnefree",
    "followers": 1700,
    "engagement_rate": 0.0206,
    "avg_views": 6458,
    "bio": "AcneFree offers a complete line of highly effective acne treatment products.",
    "recent_titles": [
      "Prom For Good With Chicago Hope Academy",
      "How To Use Therapeutic Sulfur Mask With Any Acne Skincare Routine | AcneFree",
      "How To Use Oil-Free Cleanser To Treat And Care For Acne-Prone Skin | AcneFree",
      "How To Use Adapalene Gel Acne Treatment In Your Skincare Routine | AcneFree",
      "How To Use Blackhead Removing Scrub Acne Treatment With Charcoal | AcneFree",
      "How To Use Sensitive Skin 24 Hour Clearing System For Sensitive Acne-Prone Skin | AcneFree",
      "How To Use Oil Free 24 Hour Acne 3-Step Clearing System To Get Rid Of Acne Fast | AcneFree",
      "How To Use Salicylic Acid Body Spray | Pore Clarifying Solution For Chest And Back | AcneFree",
      "How To Use Terminator 10 Severe Acne Spot Treatment To Clear Skin Fast | AcneFree",
      "How To Use Witch Hazel Mattifying Toner For Acne Prone Skin | AcneFree",
      "How To Use Severe Acne 24 Hour Clearing System To Treat Persistent Breakouts | AcneFree",
      "Affordable Dermatology-Inspired Acne Treatments for Clear Skin | AcneFree"
    ]
  },
  {
    "handle": "@dr.bryant",
    "external_id": "UCJKUcQ-xguozE9PiQJl9LiA",
    "display_name": "Dr. Bryant Esquejo, ND • Holistic Acne & Eczema",
    "url": "https://www.youtube.com/@dr.bryant",
    "followers": 1550,
    "engagement_rate": 0.006,
    "avg_views": 466,
    "bio": "California-licensed naturopathic doctor focused on balancing gut health & hormones for those with acne, eczema, & other skin concerns. No medical advice - education only.\n\nSchedule your consultation with me: https://www.drbryantesquejo.com/scheduling",
    "recent_titles": [
      "Answering a question that was submitted for my holistic skincare IG story AMA: Acne, IBS, & the gut.",
      "Vitamin D and Pollution: The Surprising Connection",
      "The Hormone-Acne Link: What You Need To Know",
      "Hypochlorous acid: The science & my thoughts as someone with acne-prone & eczema-prone skin",
      "Gut Supplements 101: Prebiotics, Probiotics, & Synbiotics. Do you know the difference?",
      "My Science-Backed Skin Barrier Routine | Weekly IG AMA",
      "What I Eat for a Resilient Skin Barrier",
      "Poop 101: What’s Normal and What’s Not | Weekly IG AMA",
      "Gut Imbalances Behind Acne: What Testing Reveals | Weekly IG AMA",
      "The link between IBS & acne and eczema | Weekly IG AMA",
      "How heartburn is linked to acne | Weekly IG AMA",
      "The link between bloat and eczema; and what to do about it"
    ]
  },
  {
    "handle": "@samaharo",
    "external_id": "UCgCDZtJUBFeWxZTS-nyEzRg",
    "display_name": "Sama Haro",
    "url": "https://www.youtube.com/@samaharo",
    "followers": 1480,
    "engagement_rate": 0.0034,
    "avg_views": 129,
    "bio": "",
    "recent_titles": [
      "6 Things I Don’t Buy Anymore — And Why",
      "5 Things I’m Changing This Fall to Make My Life Easier",
      "How to Reset Your Life When Everything Feels Overwhelming",
      "The Beauty Habits I Stopped Doing (And What I Kept)",
      "The Mistake That Made Getting Dressed So Exhausting",
      "If Your Home Feels Overwhelming, Start Here",
      "The First Thing I’d Change If I Had to Rebuild My Life",
      "I Realized I Wasn’t Buying Things… I Was Buying Hope",
      "The Question That Changed How I Make Every Decision",
      "I Didn’t Imagine Life Would Look Like This at 33 | GRWM",
      "my realistic kitchen makeover | aesthetic, functional & renter-friendly",
      "my honest dress declutter | what's actually worth keeping"
    ]
  },
  {
    "handle": "@alschmidt1106",
    "external_id": "UCqQWuVxkkL-XAKFQmMYazCQ",
    "display_name": "Al Schmidt",
    "url": "https://www.youtube.com/@alschmidt1106",
    "followers": 1480,
    "engagement_rate": 0.031,
    "avg_views": 284,
    "bio": "",
    "recent_titles": [
      "Something Totally Different with Dr  Rajiv Misquitta",
      "Something Totally Different",
      "Lunch with James (High Calcium, Bad Blood Test Results)",
      "2026 05 21 Update",
      "Al's 90th Birthday Party",
      "Lunch with Lisa (Diabetes, Weight, Cholesterol, Blood Pressure)",
      "Lunch with Ted (Cancer, Weight Loss, Dementia)",
      "Lunch with Lorna (Ovarian Cancer)",
      "2025 03 14 Al's Cancer Update",
      "Lunch with Lissa & Nate (Acne, Hormone Imbalance, IBS, Weight Loss, Kidney Cancer)",
      "Lunch with Margie (Weight Loss, Fibromyalgia, IBS, Migraine, Less Meds)",
      "2025 01 12 Update --- Cancer"
    ]
  },
  {
    "handle": "@dr.chiyen",
    "external_id": "UCifn7YeoIPlv9HJWNtZgE8A",
    "display_name": "Dr.Chiyen",
    "url": "https://www.youtube.com/@dr.chiyen",
    "followers": 1380,
    "engagement_rate": 0.0111,
    "avg_views": 1642,
    "bio": "🩺 MBBS (IMU) | Postgraduate Diploma in Dermatology\n\nA doctor (medical officer) serving in the Malaysian government healthcare system.\n\nI know what it's like to hate looking in the mirror. I struggled with severe cystic acne for years—painful, demoralising, and completely shattering my self-esteem. Nothing worked. I felt hopeless.\n\nThen I started my glow-up journey—from the inside out.\n\nI took Accutane, overhauled my lifestyle, and transformed. It took me from a shy, insecure girl who hated her reflection to a confident woman who loves herself.\n\nMy mission is to help women everywhere glow up and become their most confident self.\n\nI believe that true beauty starts from within—and that clear skin, self-care, and a healthy mindset are the foundation of that transformation.\n\nI've been where you are. I know the struggle. And I want to help you overcome it.\n\n✉️ Contact me\n\nEmail: [email removed]\n\nInstagram: https://www.instagram.com/dr.chiyen/?hl=en\n\n",
    "recent_titles": [
      "SpongeBob, Big Guy... Wait, That's NOT a Blackhead?! (Doctor Reacts)",
      "Most People Don't Know Their Skin Type – Here's How to Find Yours (Doctor Explains)",
      "Whiteheads vs Blackheads – The Hidden Difference Nobody Tells You 🤯",
      "Those White Strings on Your Nose? They're NOT Blackheads 😱",
      "Tretinoin vs Adapalene vs Epiduo vs Aklief: Which Retinoid Is Best for YOUR Acne? (Doctor Explains)",
      "81% of People Wash Their Face WRONG – Here's How to Fix It",
      "Fake Blackhead vs True Blackhead: What's REALLY on Your Nose? (Doctor Explains sebaceous filament)",
      "Girls, you don't have to try so hard",
      "3 Secrets to Clearing Your Acne Without Medication  - Doctor Reveals",
      "Cystic Acne to Clear Skin – I Became the ANIMAL 🐾✨ (KATSEYE Audio)",
      "How to Remove Whitehead FAST (Doctor's Step-by-Step Guide)",
      "I Used to Hate Looking in the Mirror"
    ]
  },
  {
    "handle": "@x7sisters296",
    "external_id": "UCaWLEqHWF0aXkBIUYMsYuQw",
    "display_name": "x7Sisters",
    "url": "https://www.youtube.com/@x7sisters296",
    "followers": 1370,
    "engagement_rate": null,
    "avg_views": null,
    "bio": "Hey, I'm Quynh (Quinn) I am 1 of 7 Sisters! I know a lot of oestrogen! =)   \nSharing with you how I manage my skincare and stress as I suffer from cystic acne, pcos and oily skin. I feel your pain if you are a fellow sufferer. We can't be rid of anything permanently but we can absolutely manage it and I will share with you how I do. \n\nWelcome, I would love for you to join our little family :) \nFollow me on insta for shorter daily doses: https://www.instagram.com/x7sisters/?hl=en",
    "recent_titles": []
  },
  {
    "handle": "@thepimplecyst8213",
    "external_id": "UCiXTFL-CWuWZWTeuRRAAMBQ",
    "display_name": "the pimple cyst",
    "url": "https://www.youtube.com/@thepimplecyst8213",
    "followers": 1040,
    "engagement_rate": 0.0841,
    "avg_views": 56065,
    "bio": "",
    "recent_titles": [
      "Shoulder cyst explosion reaches the room wall",
      "The Biggest Blackhead Umbolith Belly button",
      "Max's Infected Pimple, Popped! 3",
      "pimple cysts",
      "The biggest cyst compilation ever! Top",
      "blackhead",
      "got a bad back problem abscess",
      "crazy pimple popping,",
      "crazy pimple popping,",
      "Big Burst from Little Cyst",
      "Cyst Removal Sebaceous",
      "Cyst that lasted"
    ]
  }
];
